import type { BreedProfile } from './breedProfiles'
import type { BreedSeed } from './data'
import { expansionPhotoSources } from './breedExpansionMedia'

type ExpansionRecord = {
  id: string
  name: string
  location: string
  country: string
  lat: number
  lng: number
  flag: string
  coatColors: string
  hint: string
  fact: string
  tags: [string, string, string]
  wiki: string
  source?: string
  relatedBreedIds: string[]
  radiusKm: number
}

const records: ExpansionRecord[] = [
  { id: 'american-miniature', name: 'American Miniature Horse', location: 'United States', country: 'United States', lat: 38.5, lng: -96.0, flag: '🇺🇸', coatColors: 'Every solid color and many pinto and leopard patterns occur.', hint: 'A tiny, proportionate horse refined through generations of selection for height and balanced conformation.', fact: 'American breeders combined small European mine and estate horses with Shetland ancestry to establish a miniature breed measured by height rather than pony type.', tags: ['Miniature', 'Companion', 'American'], wiki: 'Miniature_horse', relatedBreedIds: ['falabella', 'shetland'], radiusKm: 900 },
  { id: 'anglo-arabian', name: 'Anglo-Arabian', location: 'Southwestern France', country: 'France', lat: 44.0, lng: 0.2, flag: '🇫🇷', coatColors: 'Bay, chestnut, gray, brown, and black.', hint: 'An athletic saddle horse combining Thoroughbred scope with Arabian stamina and refinement.', fact: 'Systematic French breeding at Pompadour and Tarbes made the Anglo-Arabian a major sport and military horse, with both Arabian and Thoroughbred blood required.', tags: ['Sport horse', 'Hotblood', 'French'], wiki: 'Anglo-Arabian', relatedBreedIds: ['arabian', 'thoroughbred', 'gidran'], radiusKm: 340 },
  { id: 'australian-draught', name: 'Australian Draught Horse', location: 'Southeastern Australia', country: 'Australia', lat: -36.2, lng: 144.5, flag: '🇦🇺', coatColors: 'Bay, brown, black, chestnut, gray, and roan.', hint: 'A massive working horse with great depth, strong bone, and some feather around the feet.', fact: 'The Australian Draught was consolidated from Clydesdale, Shire, Percheron, and Suffolk Punch stock selected for Australian farm and haulage conditions.', tags: ['Draft', 'Australian', 'Farm horse'], wiki: 'Australian_Draught', relatedBreedIds: ['clydesdale', 'shire', 'percheron'], radiusKm: 760 },
  { id: 'abtenauer', name: 'Abtenauer', location: 'Abtenau, Salzburg', country: 'Austria', lat: 47.56, lng: 13.35, flag: '🇦🇹', coatColors: 'Black, brown, chestnut, and blue roan; leopard spotting is not typical.', hint: 'A compact, sure-footed mountain draft horse lighter and more agile than many heavy breeds.', fact: 'This rare Austrian Noriker strain developed in the Abtenau valley, where farmers prized a low center of gravity, balance, and usefulness on steep ground.', tags: ['Mountain', 'Draft', 'Rare'], wiki: 'Abtenauer', relatedBreedIds: ['noriker', 'haflinger'], radiusKm: 90 },
  { id: 'aegidienberger', name: 'Aegidienberger', location: 'Aegidienberg', country: 'Germany', lat: 50.67, lng: 7.30, flag: '🇩🇪', coatColors: 'All solid colors, with bay, chestnut, black, and gray common.', hint: 'A small modern gaited horse created to combine tölt with greater heat tolerance.', fact: 'Walter Feldmann developed the Aegidienberger near Bonn from Icelandic Horse and Peruvian Paso blood; Germany recognized the breed in 1994.', tags: ['Gaited', 'Modern breed', 'German'], wiki: 'Aegidienberger', relatedBreedIds: ['icelandic', 'peruvian-paso'], radiusKm: 80 },
  { id: 'altai-horse', name: 'Altai Horse', location: 'Altai Mountains', country: 'Russia', lat: 50.5, lng: 86.5, flag: '🇷🇺', coatColors: 'Bay, chestnut, black, gray, and dun, often with primitive markings.', hint: 'A small, sturdy mountain horse with a broad back, hard feet, and great ability to forage.', fact: 'The Altai is an ancient Siberian mountain landrace kept outdoors by pastoral communities and selected for pack work, riding, and survival through severe winters.', tags: ['Mountain', 'Landrace', 'Hardy'], wiki: 'Altai_horse', relatedBreedIds: ['mongolian', 'bashkir-horse', 'yakutian'], radiusKm: 430 },
  { id: 'alter-real', name: 'Alter Real', location: 'Alter do Chão', country: 'Portugal', lat: 39.20, lng: -7.66, flag: '🇵🇹', coatColors: 'Bay and brown predominate, with black occasionally seen.', hint: 'A high-school riding horse of Iberian type, most often a rich bay with powerful elevated movement.', fact: 'Portugal founded the royal Alter stud in 1748 with selected Andalusian mares; the Alter Real remains a distinct Lusitano strain associated with classical equitation.', tags: ['Baroque', 'Royal stud', 'Dressage'], wiki: 'Alter_Real', relatedBreedIds: ['lusitano', 'andalusian', 'lipizzan'], radiusKm: 90 },
  { id: 'anglo-kabarda', name: 'Anglo-Kabarda', location: 'North Caucasus', country: 'Russia', lat: 43.5, lng: 43.6, flag: '🇷🇺', coatColors: 'Bay, dark bay, brown, and black are most common.', hint: 'A rangy mountain saddle horse blending Thoroughbred speed with a sure-footed Caucasian base.', fact: 'The Anglo-Kabarda was standardized by crossing Kabarda mares with Thoroughbred stallions while retaining enough native ancestry for mountain endurance and soundness.', tags: ['Mountain', 'Sport horse', 'Caucasian'], wiki: 'Anglo-Kabarda', relatedBreedIds: ['kabarda', 'thoroughbred', 'karachay'], radiusKm: 300 },
  { id: 'arravani', name: 'Arravani', location: 'Peloponnese', country: 'Greece', lat: 37.5, lng: 22.3, flag: '🇬🇷', coatColors: 'Bay, brown, black, chestnut, gray, and roan.', hint: 'A light, willing Greek horse often able to perform a comfortable lateral gait.', fact: 'The Arravani is a rare Greek gaited breed shaped by farm, pack, and riding work; preservation breeders maintain its easy amble and practical temperament.', tags: ['Gaited', 'Greek', 'Rare'], wiki: 'Arravani', source: 'https://www.arravani.de/rasseportrait/ursprung-der-rasse/', relatedBreedIds: ['pindos', 'messara'], radiusKm: 260 },
  { id: 'auvergne-horse', name: 'Auvergne Horse', location: 'Auvergne', country: 'France', lat: 45.55, lng: 3.1, flag: '🇫🇷', coatColors: 'Bay or seal brown with black points and limited white.', hint: 'A compact, deep-bodied mountain horse with strong limbs and an exceptionally calm nature.', fact: 'The Auvergne Horse is a revived regional breed from France’s Massif Central, where its ancestors carried riders and loads across volcanic uplands.', tags: ['Mountain', 'French', 'Regional'], wiki: 'Auvergne_horse', relatedBreedIds: ['merens', 'henson-horse'], radiusKm: 240 },
  { id: 'auxois', name: 'Auxois', location: 'Auxois, Burgundy', country: 'France', lat: 47.3, lng: 4.5, flag: '🇫🇷', coatColors: 'Bay and roan are characteristic; chestnut also occurs.', hint: 'A broad, powerful French draft horse with Ardennais ancestry and relatively little feather.', fact: 'Farmers in Burgundy developed the Auxois from local mares and Ardennais stallions for heavy fieldwork in the fertile Auxois country.', tags: ['Draft', 'French', 'Rare'], wiki: 'Auxois', relatedBreedIds: ['ardennais', 'trait-du-nord'], radiusKm: 170 },
  { id: 'banker-horse', name: 'Banker Horse', location: 'Outer Banks, North Carolina', country: 'United States', lat: 35.6, lng: -75.5, flag: '🇺🇸', coatColors: 'Bay, brown, chestnut, and black, sometimes with white markings.', hint: 'A small, sturdy feral horse adapted to barrier-island heat, marshes, and sparse forage.', fact: 'Banker horses live in several managed Outer Banks herds and descend from domestic horses brought to the Carolina coast centuries ago.', tags: ['Feral', 'Island', 'Colonial'], wiki: 'Banker_horse', relatedBreedIds: ['chincoteague-pony', 'spanish-mustang', 'florida-cracker'], radiusKm: 190 },
  { id: 'basotho-pony', name: 'Basotho Pony', location: 'Lesotho Highlands', country: 'Lesotho', lat: -29.5, lng: 28.2, flag: '🇱🇸', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A sure-footed southern African mountain pony known for stamina on steep, rocky tracks.', fact: 'The Basotho Pony developed from Cape horses and other imports under the demanding riding culture and high-altitude conditions of Lesotho.', tags: ['Mountain pony', 'African', 'Endurance'], wiki: 'Basotho_pony', relatedBreedIds: ['cape-boerperd', 'namib-desert-horse', 'barb'], radiusKm: 280 },
  { id: 'batak-pony', name: 'Batak Pony', location: 'Northern Sumatra', country: 'Indonesia', lat: 2.5, lng: 99.0, flag: '🇮🇩', coatColors: 'Bay, chestnut, brown, black, gray, dun, and pinto.', hint: 'A refined but hardy Indonesian pony with a light frame and notable spirit.', fact: 'Batak communities of northern Sumatra bred this pony for riding, pack work, and prestige, with Arabian influence often credited for its refinement.', tags: ['Indonesian', 'Pony', 'Riding'], wiki: 'Batak_pony', relatedBreedIds: ['sandalwood-pony', 'java-pony', 'arabian'], radiusKm: 320 },
  { id: 'belgian-warmblood', name: 'Belgian Warmblood', location: 'Belgium', country: 'Belgium', lat: 50.8, lng: 4.6, flag: '🇧🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A powerful, modern jumping horse with a rectangular frame and athletic hind end.', fact: 'Belgian breeders established the BWP studbook in the 1950s, combining native mares with leading European sport-horse bloodlines.', tags: ['Warmblood', 'Show jumping', 'Belgian'], wiki: 'Belgian_Warmblood', relatedBreedIds: ['dutch-warmblood', 'selle-francais', 'holsteiner'], radiusKm: 220 },
  { id: 'kaimanawa', name: 'Kaimanawa Horse', location: 'Central North Island', country: 'New Zealand', lat: -39.2, lng: 175.7, flag: '🇳🇿', coatColors: 'Bay, chestnut, brown, black, gray, roan, and pinto.', hint: 'A compact, sure-footed feral horse with hard feet, strong bone, and a highly variable practical build.', fact: 'Kaimanawa horses descend from domestic animals released or escaped in New Zealand’s central North Island and have lived as managed wild herds since the nineteenth century.', tags: ['Feral', 'New Zealand', 'Hardy'], wiki: 'Kaimanawa_horses', relatedBreedIds: ['brumby', 'mustang', 'waler'], radiusKm: 260 },
  { id: 'bosnian-mountain', name: 'Bosnian Mountain Horse', location: 'Bosnian Dinaric Alps', country: 'Bosnia and Herzegovina', lat: 44.0, lng: 17.8, flag: '🇧🇦', coatColors: 'Bay, brown, black, chestnut, gray, and dun.', hint: 'A small, tough pack horse with a long body, strong loin, and exceptionally sure feet.', fact: 'This Balkan mountain breed was standardized from hardy local horses and improved with controlled Arabian influence for military and agricultural use.', tags: ['Mountain', 'Pack horse', 'Balkan'], wiki: 'Bosnian_Mountain_Horse', relatedBreedIds: ['hucul', 'pindos', 'nonius'], radiusKm: 360 },
  { id: 'budyonny', name: 'Budyonny Horse', location: 'Rostov Oblast', country: 'Russia', lat: 47.5, lng: 40.0, flag: '🇷🇺', coatColors: 'Chestnut predominates, often with a golden sheen; bay, brown, and black occur.', hint: 'A tall, athletic Russian saddle horse, frequently bright chestnut and built for speed and stamina.', fact: 'Soviet studs created the Budyonny from Don and Thoroughbred stock as a durable cavalry mount that later developed into a versatile sport horse.', tags: ['Cavalry', 'Sport horse', 'Russian'], wiki: 'Budyonny_horse', relatedBreedIds: ['don-horse', 'thoroughbred', 'ukrainian-riding'], radiusKm: 390 },
  { id: 'burguete', name: 'Burguete Horse', location: 'Navarrese Pyrenees', country: 'Spain', lat: 42.9, lng: -1.3, flag: '🇪🇸', coatColors: 'Chestnut and bay are usual, often with flaxen manes.', hint: 'A medium-heavy mountain horse with deep body, strong bone, and agile movement.', fact: 'The Burguete developed in Navarre by crossing local Jaca Navarra mares with larger draft breeds while retaining adaptation to mountain pastures.', tags: ['Mountain', 'Draft', 'Spanish'], wiki: 'Burguete_horse', relatedBreedIds: ['jaca-navarra', 'breton'], radiusKm: 130 },
  { id: 'belarus-harness', name: 'Belarus Harness Horse', location: 'Belarus', country: 'Belarus', lat: 53.4, lng: 27.8, flag: '🇧🇾', coatColors: 'Bay, chestnut, brown, black, and dun.', hint: 'A compact, muscular harness horse with a long body and unusually good endurance for farm work.', fact: 'Belarusian breeders developed this multipurpose horse from local forest stock crossed with Ardennais, Brabançon, and other harness breeds.', tags: ['Harness', 'Farm horse', 'Belarusian'], wiki: 'Belarusian_Harness_Horse', relatedBreedIds: ['ardennais', 'russian-heavy-draft', 'sokolski'], radiusKm: 540 },
  { id: 'freiberger', name: 'Freiberger', location: 'Franches-Montagnes, Jura', country: 'Switzerland', lat: 47.2, lng: 7.0, flag: '🇨🇭', coatColors: 'Bay and chestnut predominate; brown, black, gray, and roan occur.', hint: 'A compact light-draft horse with a calm nature, active movement, and enough athleticism for riding or driving.', fact: 'The Freiberger is Switzerland’s last native horse breed, developed in the Jura for farms, artillery, transport, and modern all-purpose riding and driving.', tags: ['Light draft', 'Swiss', 'Versatile'], wiki: 'Freiberger', relatedBreedIds: ['comtois', 'haflinger', 'cleveland-bay'], radiusKm: 150 },
  { id: 'carolina-marsh-tacky', name: 'Carolina Marsh Tacky', location: 'South Carolina Lowcountry', country: 'United States', lat: 32.5, lng: -80.8, flag: '🇺🇸', coatColors: 'Bay, black, chestnut, dun, grullo, roan, and pinto.', hint: 'A small Spanish-type horse adapted to heat, mud, marshland, and long hours under saddle.', fact: 'The Marsh Tacky descends from Colonial Spanish horses used in the South Carolina Lowcountry for herding, hunting, transport, and military service.', tags: ['Colonial Spanish', 'Marsh', 'Rare'], wiki: 'Carolina_Marsh_Tacky', relatedBreedIds: ['florida-cracker', 'spanish-mustang', 'banker-horse'], radiusKm: 260 },
  { id: 'catria', name: 'Catria Horse', location: 'Monte Catria, Marche', country: 'Italy', lat: 43.5, lng: 12.7, flag: '🇮🇹', coatColors: 'Bay, black, chestnut, and gray.', hint: 'A solid, sure-footed Italian mountain horse suited to both saddle and light agricultural work.', fact: 'The Catria comes from the central Apennines, where local horses were influenced by Maremmano and other military and mountain stock.', tags: ['Mountain', 'Italian', 'Versatile'], wiki: 'Catria_horse', relatedBreedIds: ['maremmano', 'bardigiano'], radiusKm: 160 },
  { id: 'chincoteague-pony', name: 'Chincoteague Pony', location: 'Assateague Island', country: 'United States', lat: 37.9, lng: -75.35, flag: '🇺🇸', coatColors: 'Most colors occur, with pinto patterns especially common.', hint: 'A compact feral-island pony, often brightly pinto, shaped by salt marsh and coastal weather.', fact: 'The famous Chincoteague ponies are managed herds living on Assateague Island; annual swims and auctions support herd control and local tradition.', tags: ['Feral', 'Island pony', 'Pinto'], wiki: 'Chincoteague_Pony', relatedBreedIds: ['banker-horse', 'mustang', 'shetland'], radiusKm: 120 },
  { id: 'chilean-horse', name: 'Chilean Horse', location: 'Central Chile', country: 'Chile', lat: -34.3, lng: -71.0, flag: '🇨🇱', coatColors: 'Bay, chestnut, black, brown, gray, dun, and roan.', hint: 'A compact, muscular cow horse with a deep chest, sloping croup, and very quick turns.', fact: 'Also called the Chilean Corralero, this old South American breed was selected from Iberian stock for ranch work and the uniquely Chilean rodeo.', tags: ['Stock horse', 'Chilean', 'Rodeo'], wiki: 'Chilean_horse', relatedBreedIds: ['criollo', 'peruvian-paso', 'mangalarga-marchador'], radiusKm: 620 },
  { id: 'irish-sport-horse', name: 'Irish Sport Horse', location: 'Ireland', country: 'Ireland', lat: 53.3, lng: -8.2, flag: '🇮🇪', coatColors: 'Bay, chestnut, gray, brown, black, and roan; white markings are common.', hint: 'A powerful, willing competition horse combining substantial bone with speed, scope, and courage over fences.', fact: 'The Irish Sport Horse grew from crossing Irish Draught mares with Thoroughbred and later European sport-horse lines, producing internationally successful jumpers and eventers.', tags: ['Sport horse', 'Eventing', 'Irish'], wiki: 'Irish_Sport_Horse', relatedBreedIds: ['irish-draught', 'thoroughbred', 'selle-francais'], radiusKm: 480 },
  { id: 'corsican-horse', name: 'Corsican Horse', location: 'Corsica', country: 'France', lat: 42.1, lng: 9.0, flag: '🇫🇷', coatColors: 'Bay, dark bay, brown, and black, with minimal white.', hint: 'A small, narrow mountain horse with hard feet, a short back, and great agility on rough ground.', fact: 'Known locally as U Cavallu Corsu, the Corsican Horse is an island landrace officially recognized in 2012 after centuries as a riding and pack animal.', tags: ['Island', 'Mountain', 'Landrace'], wiki: 'Corsican_horse', relatedBreedIds: ['giara', 'sardinian-anglo-arab', 'maremmano'], radiusKm: 140 },
  { id: 'croatian-coldblood', name: 'Croatian Coldblood', location: 'Central and northern Croatia', country: 'Croatia', lat: 45.6, lng: 16.3, flag: '🇭🇷', coatColors: 'Bay, brown, black, chestnut, and roan.', hint: 'A broad, low-set draft horse with abundant muscle and a calm working temperament.', fact: 'Croatian farmers developed this heavy breed from local mares crossed chiefly with Noriker, Ardennais, and Brabant-type stallions.', tags: ['Draft', 'Croatian', 'Farm horse'], wiki: 'Croatian_Coldblood', relatedBreedIds: ['noriker', 'ardennais', 'medimurje'], radiusKm: 330 },
  { id: 'dole-gudbrandsdal', name: 'Døle Gudbrandsdal', location: 'Gudbrandsdalen', country: 'Norway', lat: 61.5, lng: 9.2, flag: '🇳🇴', coatColors: 'Black and brown predominate; bay and chestnut also occur.', hint: 'A compact Norwegian draft horse with immense pulling power, sure feet, and an active trot.', fact: 'The Døle developed in Norway’s Gudbrandsdal valley for farm and forestry work; its lighter trotting branch became the Coldblood Trotter.', tags: ['Draft', 'Nordic', 'Forestry'], wiki: 'D%C3%B8lehest', relatedBreedIds: ['north-swedish', 'fjord', 'finnhorse'], radiusKm: 270 },
  { id: 'danish-warmblood', name: 'Danish Warmblood', location: 'Denmark', country: 'Denmark', lat: 56.0, lng: 9.3, flag: '🇩🇰', coatColors: 'Bay, chestnut, black, brown, and gray.', hint: 'An elegant, long-legged sport horse selected especially for dressage and jumping ability.', fact: 'Denmark formed its modern warmblood registry in the 1960s, blending native mares with leading European and Thoroughbred performance lines.', tags: ['Warmblood', 'Dressage', 'Danish'], wiki: 'Danish_Warmblood', relatedBreedIds: ['frederiksborg', 'holsteiner', 'dutch-warmblood'], radiusKm: 330 },
  { id: 'misaki-horse', name: 'Misaki Horse', location: 'Cape Toi, Miyazaki', country: 'Japan', lat: 31.37, lng: 131.34, flag: '🇯🇵', coatColors: 'Bay, dark bay, brown, and black, usually with very little white.', hint: 'A small, compact feral horse with a coarse mane, hard feet, and a practical unrefined build.', fact: 'The Misaki is one of Japan’s native breeds and has lived under protected, free-ranging management around Cape Toi since a breeding pasture was established in 1697.', tags: ['Japanese native', 'Feral', 'Protected'], wiki: 'Misaki_horse', relatedBreedIds: ['kiso-horse', 'noma-horse', 'yonaguni-horse'], radiusKm: 80 },
  { id: 'dutch-harness', name: 'Dutch Harness Horse', location: 'Netherlands', country: 'Netherlands', lat: 52.2, lng: 5.4, flag: '🇳🇱', coatColors: 'Bay, chestnut, brown, black, and gray; white markings are common.', hint: 'A showy carriage horse with a high-set neck, powerful hindquarters, and extravagant knee action.', fact: 'Known as the Tuigpaard, this Dutch breed preserves the animated harness type within the KWPN studbook and is selected for spectacular carriage movement.', tags: ['Harness', 'High action', 'Dutch'], wiki: 'Dutch_Harness_Horse', relatedBreedIds: ['gelderlander', 'hackney-horse', 'dutch-warmblood'], radiusKm: 250 },
  { id: 'dutch-warmblood', name: 'Dutch Warmblood', location: 'Netherlands', country: 'Netherlands', lat: 52.1, lng: 5.3, flag: '🇳🇱', coatColors: 'Bay, chestnut, brown, black, and gray; tobiano occurs in some lines.', hint: 'A tall, modern sport horse with uphill balance and exceptional jumping or dressage movement.', fact: 'The KWPN developed from Gelderlander and Groningen farm horses refined with Thoroughbred and European warmblood lines for elite sport.', tags: ['Warmblood', 'Sport horse', 'Dutch'], wiki: 'Dutch_Warmblood', relatedBreedIds: ['gelderlander', 'groningen', 'belgian-warmblood'], radiusKm: 260 },
  { id: 'tori-horse', name: 'Tori Horse', location: 'Tori, Pärnu County', country: 'Estonia', lat: 58.48, lng: 24.82, flag: '🇪🇪', coatColors: 'Chestnut is most common, followed by bay and brown; black and roan occur.', hint: 'A substantial but active all-purpose horse with a deep body, strong bone, and willing harness or riding movement.', fact: 'The Tori breed was founded at Estonia’s Tori stud from native mares and the Norfolk Roadster stallion Hetman, later developing both lighter sport and heavier utility types.', tags: ['All-purpose', 'Estonian', 'Harness'], wiki: 'Tori_(horse)', relatedBreedIds: ['estonian-native', 'hackney-horse', 'belarus-harness'], radiusKm: 170 },
  { id: 'estonian-native', name: 'Estonian Native Horse', location: 'Estonian islands and coast', country: 'Estonia', lat: 58.7, lng: 23.5, flag: '🇪🇪', coatColors: 'Bay, chestnut, black, gray, dun, and silver dapple.', hint: 'A small, hardy northern horse with a thick mane, efficient movement, and durable feet.', fact: 'Also called the Eesti hobune, this ancient native breed survived especially on Estonia’s western islands as an economical farm and riding horse.', tags: ['Native breed', 'Baltic', 'Hardy'], wiki: 'Estonian_Native', relatedBreedIds: ['zemaitukas', 'finnhorse', 'tori-horse'], radiusKm: 310 },
  { id: 'faroe-pony', name: 'Faroe Pony', location: 'Faroe Islands', country: 'Faroe Islands', lat: 62.0, lng: -6.8, flag: '🇫🇴', coatColors: 'Bay, black, and chestnut, often with mealy points or silver dilution.', hint: 'A very small, powerful island pony with a dense coat and a notably thick mane and tail.', fact: 'The Faroe Pony is an isolated North Atlantic breed that nearly vanished in the 20th century; a tiny conservation population preserves its distinct genetics.', tags: ['Island pony', 'Nordic', 'Critical'], wiki: 'Faroe_pony', relatedBreedIds: ['icelandic', 'shetland', 'nordlandshest'], radiusKm: 90 },
  { id: 'frederiksborg', name: 'Frederiksborg Horse', location: 'Zealand', country: 'Denmark', lat: 55.9, lng: 12.3, flag: '🇩🇰', coatColors: 'Chestnut is characteristic, usually with flaxen mane and generous white markings.', hint: 'A powerful, elegant carriage horse most often bright chestnut with a high-set neck.', fact: 'Founded at the royal Frederiksborg stud in the 16th century, this Danish breed influenced European carriage and riding horses before becoming rare.', tags: ['Baroque', 'Carriage', 'Danish'], wiki: 'Frederiksborg_horse', relatedBreedIds: ['knabstrupper', 'danish-warmblood', 'kladruber'], radiusKm: 100 },
  { id: 'marismeno', name: 'Marismeño', location: 'Doñana marshes', country: 'Spain', lat: 37.05, lng: -6.45, flag: '🇪🇸', coatColors: 'Gray, bay, brown, black, and chestnut, with white markings permitted.', hint: 'A hardy marsh and cattle horse with a functional frame, strong legs, and agility over wet ground.', fact: 'The Marismeño is a rare native breed of the Guadalquivir marshes, maintained in semi-feral herds and traditionally gathered during the annual Saca de las Yeguas.', tags: ['Marsh horse', 'Spanish', 'Semi-feral'], wiki: 'Marisme%C3%B1o', relatedBreedIds: ['retuerta', 'camargue', 'andalusian'], radiusKm: 130 },
  { id: 'galiceno', name: 'Galiceno', location: 'Mexico', country: 'Mexico', lat: 22.5, lng: -102.0, flag: '🇲🇽', coatColors: 'Bay, chestnut, black, brown, gray, dun, and roan.', hint: 'A small but horse-proportioned Mexican mount with quick feet and naturally smooth gaits.', fact: 'The Galiceno descends from Iberian horses brought to Mexico and was selected as a tough ranch, trail, and family riding horse.', tags: ['Mexican', 'Gaited', 'Ranch horse'], wiki: 'Galiceno', relatedBreedIds: ['spanish-mustang', 'florida-cracker', 'azteca-horse'], radiusKm: 900 },
  { id: 'gelderlander', name: 'Gelderlander', location: 'Gelderland', country: 'Netherlands', lat: 52.0, lng: 5.9, flag: '🇳🇱', coatColors: 'Chestnut is especially common, often with bold white; bay, brown, black, and gray occur.', hint: 'A substantial all-purpose horse with a high-set neck and both carriage action and riding ability.', fact: 'The Gelderlander arose as the versatile farm and carriage horse of Gelderland and became a foundation of both the Dutch Warmblood and Dutch Harness Horse.', tags: ['Warmblood', 'Carriage', 'Dutch'], wiki: 'Gelderlander', relatedBreedIds: ['dutch-warmblood', 'dutch-harness', 'groningen'], radiusKm: 130 },
  { id: 'groningen', name: 'Groningen Horse', location: 'Groningen', country: 'Netherlands', lat: 53.2, lng: 6.6, flag: '🇳🇱', coatColors: 'Black, dark bay, and brown predominate; chestnut occurs.', hint: 'A heavy warmblood with great depth, strong bone, a powerful hind end, and a calm character.', fact: 'The Groningen developed as a strong northern Dutch farm and carriage horse and later contributed substantially to the Dutch Warmblood.', tags: ['Heavy warmblood', 'Farm horse', 'Dutch'], wiki: 'Groningen_horse', relatedBreedIds: ['gelderlander', 'dutch-warmblood', 'friesian'], radiusKm: 120 },
  { id: 'hackney-horse', name: 'Hackney Horse', location: 'Norfolk and Yorkshire', country: 'England', lat: 53.0, lng: -1.3, flag: '🇬🇧', coatColors: 'Bay, brown, black, and chestnut, often with white markings.', hint: 'A brilliant carriage horse with extreme flexion, elevated trot, and a proud arched neck.', fact: 'The Hackney grew from fast English road trotters, especially Norfolk and Yorkshire stock, and became the definitive high-action harness horse.', tags: ['Harness', 'High action', 'English'], wiki: 'Hackney_horse', relatedBreedIds: ['dutch-harness', 'cleveland-bay', 'standardbred'], radiusKm: 320 },
  { id: 'henson-horse', name: 'Henson Horse', location: 'Baie de Somme', country: 'France', lat: 50.2, lng: 1.6, flag: '🇫🇷', coatColors: 'Dun with a dark dorsal stripe and dark mane, tail, and lower legs.', hint: 'A modern dun leisure horse with primitive markings, a sturdy frame, and an easy outdoor temperament.', fact: 'The Henson was created in Picardy from Fjord crosses selected for trail riding and management of the wetlands around the Baie de Somme.', tags: ['Leisure horse', 'Dun', 'French'], wiki: 'Henson_horse', relatedBreedIds: ['fjord', 'camargue', 'auvergne-horse'], radiusKm: 110 },
  { id: 'hispano-breton', name: 'Hispano-Bretón', location: 'Northern Spanish mountains', country: 'Spain', lat: 42.6, lng: -4.0, flag: '🇪🇸', coatColors: 'Chestnut, bay, black, and roan.', hint: 'A compact Spanish draft horse with a broad chest, strong quarters, and thick mountain coat.', fact: 'The Hispano-Bretón developed when Breton stallions were crossed with local mares in northern Spain for agricultural and meat production.', tags: ['Draft', 'Spanish', 'Mountain'], wiki: 'Hispano-Bret%C3%B3n', relatedBreedIds: ['breton', 'burguete', 'asturcon'], radiusKm: 500 },
  { id: 'holsteiner', name: 'Holsteiner', location: 'Schleswig-Holstein', country: 'Germany', lat: 54.2, lng: 9.8, flag: '🇩🇪', coatColors: 'Bay, brown, black, chestnut, and gray.', hint: 'A powerful sport horse with a strong topline and world-famous jumping technique.', fact: 'One of Germany’s oldest warmbloods, the Holsteiner evolved from marshland cavalry and coach horses into an elite show-jumping breed.', tags: ['Warmblood', 'Show jumping', 'German'], wiki: 'Holsteiner', relatedBreedIds: ['oldenburg', 'westphalian', 'trakehner'], radiusKm: 230 },
  { id: 'hanoverian', name: 'Hanoverian', location: 'Lower Saxony', country: 'Germany', lat: 52.6, lng: 9.2, flag: '🇩🇪', coatColors: 'Bay, chestnut, black, brown, and gray.', hint: 'A large, athletic sport horse with elastic gaits, a powerful hind end, and a steady trainable character.', fact: 'The Hanoverian traces to the state stud at Celle, founded in 1735, and evolved from a cavalry and farm horse into one of the world’s most influential sport breeds.', tags: ['Warmblood', 'Sport horse', 'German'], wiki: 'Hanoverian_horse', relatedBreedIds: ['westphalian', 'oldenburg', 'holsteiner'], radiusKm: 240 },
  { id: 'iomud', name: 'Iomud', location: 'Daşoguz and northern Turkmenistan', country: 'Turkmenistan', lat: 41.2, lng: 58.3, flag: '🇹🇲', coatColors: 'Gray and bay predominate; chestnut, black, and golden dilutes occur.', hint: 'A lean desert riding horse resembling its Akhal-Teke neighbor but generally more compact.', fact: 'The Iomud was developed by the Yomut Turkmen for raiding, travel, and endurance around the eastern Caspian and Khorezm oases.', tags: ['Desert', 'Turkmen', 'Endurance'], wiki: 'Iomud', relatedBreedIds: ['akhal-teke', 'karabair', 'arabian'], radiusKm: 480 },
  { id: 'jaca-navarra', name: 'Jaca Navarra', location: 'Navarrese Pyrenees', country: 'Spain', lat: 42.9, lng: -1.5, flag: '🇪🇸', coatColors: 'Bay and black, usually with little white.', hint: 'A small, dark, primitive mountain horse with a compact body and tough limbs.', fact: 'The Jaca Navarra is an endangered native horse of Navarre, traditionally living semi-ferally and working in mountain agriculture.', tags: ['Mountain', 'Primitive', 'Spanish'], wiki: 'Jaca_Navarra', relatedBreedIds: ['burguete', 'pottok', 'losino'], radiusKm: 130 },
  { id: 'java-pony', name: 'Java Pony', location: 'Java', country: 'Indonesia', lat: -7.5, lng: 110.0, flag: '🇮🇩', coatColors: 'Bay, chestnut, brown, black, gray, dun, and pinto.', hint: 'A small, lightly built island pony known for heat tolerance and tireless carriage work.', fact: 'The Java Pony descends from Southeast Asian stock influenced by Arab and other imported horses during centuries of maritime trade.', tags: ['Island pony', 'Driving', 'Indonesian'], wiki: 'Java_pony', relatedBreedIds: ['batak-pony', 'sandalwood-pony', 'arabian'], radiusKm: 430 },
  { id: 'kabarda', name: 'Kabarda', location: 'North Caucasus', country: 'Russia', lat: 43.4, lng: 43.2, flag: '🇷🇺', coatColors: 'Bay, dark bay, brown, and black, with minimal white.', hint: 'A sure-footed Caucasian mountain horse with a long back, strong loins, and remarkable balance.', fact: 'The Kabarda was bred for centuries by Circassian peoples for mountain travel, war, and endurance over steep, rocky ground.', tags: ['Mountain', 'Caucasian', 'Endurance'], wiki: 'Kabarda_horse', relatedBreedIds: ['anglo-kabarda', 'karachay', 'karabakh'], radiusKm: 300 },
  { id: 'karabair', name: 'Karabair', location: 'Uzbekistan', country: 'Uzbekistan', lat: 40.7, lng: 66.9, flag: '🇺🇿', coatColors: 'Bay, chestnut, gray, black, and brown.', hint: 'A versatile Central Asian horse combining a strong riding frame with light harness ability.', fact: 'The Karabair developed in the oases and steppe of Uzbekistan from ancient local horses influenced by Arabian, Persian, and Turkmen blood.', tags: ['Central Asian', 'Riding', 'Endurance'], wiki: 'Karabair', relatedBreedIds: ['akhal-teke', 'iomud', 'kyrgyz-horse'], radiusKm: 720 },
  { id: 'karachay', name: 'Karachay Horse', location: 'Northwestern Caucasus', country: 'Russia', lat: 43.8, lng: 42.0, flag: '🇷🇺', coatColors: 'Black, bay, dark bay, and brown predominate.', hint: 'A powerful, dark mountain horse famous for sure-footedness at extreme altitude.', fact: 'Karachay people developed this breed in the high northwestern Caucasus for riding and pack work across passes where balance and stamina were essential.', tags: ['Mountain', 'Caucasian', 'Hardy'], wiki: 'Karachay_horse', relatedBreedIds: ['kabarda', 'anglo-kabarda', 'don-horse'], radiusKm: 280 },
  { id: 'kiger-mustang', name: 'Kiger Mustang', location: 'Southeastern Oregon', country: 'United States', lat: 42.7, lng: -118.6, flag: '🇺🇸', coatColors: 'Dun and grullo predominate, with dorsal stripes and leg barring.', hint: 'A refined feral horse usually dun, with strong primitive markings and an Iberian outline.', fact: 'The Kiger Mustang comes from Oregon herds selected for a distinctive Spanish-colonial type and conserved in dedicated herd management areas.', tags: ['Feral', 'Dun', 'Spanish colonial'], wiki: 'Kiger_mustang', relatedBreedIds: ['mustang', 'spanish-mustang', 'sorraia'], radiusKm: 260 },
  { id: 'kinsky-horse', name: 'Kinsky Horse', location: 'Chlumec nad Cidlinou', country: 'Czechia', lat: 50.15, lng: 15.46, flag: '🇨🇿', coatColors: 'Palomino and buckskin are celebrated; bay, chestnut, and brown also occur.', hint: 'An elegant Czech sport horse especially associated with luminous golden coats.', fact: 'The Kinsky family developed this warmblood at Chlumec from high-quality local and Thoroughbred stock, maintaining a famous cream-dilute tradition.', tags: ['Warmblood', 'Golden coat', 'Czech'], wiki: 'Kinsky_horse', relatedBreedIds: ['trakehner', 'thoroughbred', 'kisber-felver'], radiusKm: 100 },
  { id: 'kiso-horse', name: 'Kiso Horse', location: 'Kiso Valley', country: 'Japan', lat: 35.9, lng: 137.7, flag: '🇯🇵', coatColors: 'Bay, dark bay, black, and chestnut, often with a dorsal stripe.', hint: 'A small Japanese native horse with a long body, steep croup, and strong, short legs.', fact: 'The Kiso is the only surviving native breed of Honshu and once served farms, mountain transport, and samurai in the Kiso Valley.', tags: ['Japanese native', 'Mountain', 'Rare'], wiki: 'Kiso_Horse', relatedBreedIds: ['noma-horse', 'yonaguni-horse', 'mongolian'], radiusKm: 110 },
  { id: 'kyrgyz-horse', name: 'Kyrgyz Horse', location: 'Tian Shan', country: 'Kyrgyzstan', lat: 41.5, lng: 74.7, flag: '🇰🇬', coatColors: 'Bay, chestnut, gray, black, dun, and roan.', hint: 'A compact high-mountain horse able to travel, graze, and work at great altitude.', fact: 'Kyrgyz horses remain central to pastoral life in the Tian Shan, providing transport, sport, meat, and fermented mare’s milk.', tags: ['Mountain', 'Nomadic', 'Central Asian'], wiki: 'Kyrgyz_Horse', relatedBreedIds: ['mongolian', 'altai-horse', 'karabair'], radiusKm: 620 },
  { id: 'latvian-horse', name: 'Latvian Horse', location: 'Latvia', country: 'Latvia', lat: 56.9, lng: 24.6, flag: '🇱🇻', coatColors: 'Bay, brown, black, and chestnut; gray is uncommon.', hint: 'A substantial Baltic warmblood with strong bone and both riding and harness aptitude.', fact: 'The Latvian Horse developed from local mares crossed with Oldenburg, Hanoverian, and other European stallions, producing sport and heavier harness types.', tags: ['Warmblood', 'Baltic', 'Versatile'], wiki: 'Latvian_horse', relatedBreedIds: ['oldenburg', 'estonian-native', 'trakehner'], radiusKm: 330 },
  { id: 'bavarian-warmblood', name: 'Bavarian Warmblood', location: 'Bavaria', country: 'Germany', lat: 48.9, lng: 11.4, flag: '🇩🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A modern athletic sport horse with an expressive head, elastic movement, and powerful hindquarters.', fact: 'The Bavarian Warmblood developed from the older Rottaler population and was reshaped after World War II with leading German and European sport-horse bloodlines.', tags: ['Warmblood', 'Sport horse', 'Versatile'], wiki: 'Bavarian_Warmblood', relatedBreedIds: ['hanoverian', 'westphalian', 'oldenburg'], radiusKm: 320 },
  { id: 'losino', name: 'Losino Horse', location: 'Losa Valley, Burgos', country: 'Spain', lat: 42.9, lng: -3.3, flag: '🇪🇸', coatColors: 'Solid black, sometimes fading in the sun; white markings are minimal.', hint: 'A small, uniformly black Iberian mountain horse with a coarse mane and agile build.', fact: 'The Losino is an ancient, endangered landrace from northern Burgos, preserved from a remnant semi-feral population of fewer than a hundred animals.', tags: ['Primitive', 'Black coat', 'Spanish'], wiki: 'Losino_horse', relatedBreedIds: ['asturcon', 'jaca-navarra', 'pottok'], radiusKm: 110 },
  { id: 'malopolski', name: 'Małopolski', location: 'Lesser Poland', country: 'Poland', lat: 50.3, lng: 20.3, flag: '🇵🇱', coatColors: 'Bay, chestnut, gray, black, and brown.', hint: 'A refined Polish saddle horse with Arabian-influenced endurance and Thoroughbred athleticism.', fact: 'The Małopolski developed from southeastern Polish mare families crossed with Arabian, Anglo-Arabian, and Thoroughbred stock for cavalry and sport.', tags: ['Warmblood', 'Polish', 'Anglo-Arabian'], wiki: 'Malopolski', relatedBreedIds: ['anglo-arabian', 'shagya-arabian', 'thoroughbred'], radiusKm: 380 },
  { id: 'mangalarga-paulista', name: 'Mangalarga Paulista', location: 'São Paulo state', country: 'Brazil', lat: -22.5, lng: -48.5, flag: '🇧🇷', coatColors: 'Bay, chestnut, gray, black, palomino, buckskin, and pinto.', hint: 'A smooth-riding Brazilian horse with a lighter sportier outline and diagonal marcha gait.', fact: 'The Mangalarga Paulista split from the Minas Gerais Marchador tradition as São Paulo breeders selected a taller, different-gaited ranch and riding horse.', tags: ['Gaited', 'Brazilian', 'Ranch horse'], wiki: 'Mangalarga', relatedBreedIds: ['mangalarga-marchador', 'campolina'], radiusKm: 550 },
  { id: 'manipuri-pony', name: 'Manipuri Pony', location: 'Manipur', country: 'India', lat: 24.8, lng: 93.9, flag: '🇮🇳', coatColors: 'Bay, brown, chestnut, gray, and pinto.', hint: 'A quick, compact Indian pony celebrated for agility, stamina, and polo ability.', fact: 'The Manipuri Pony is an ancient northeastern Indian breed inseparable from the region’s cavalry history and the development of modern polo.', tags: ['Polo', 'Indian', 'Endangered'], wiki: 'Manipuri_Pony', relatedBreedIds: ['spiti-horse', 'mongolian', 'marwari'], radiusKm: 230 },
  { id: 'marajoara', name: 'Marajoara Horse', location: 'Marajó Island', country: 'Brazil', lat: -0.9, lng: -49.5, flag: '🇧🇷', coatColors: 'Bay, chestnut, brown, black, gray, and roan.', hint: 'A tough ranch horse adapted to tropical heat, seasonal flooding, mud, and long cattle work.', fact: 'The Marajoara developed on the vast Amazon-delta island of Marajó from Iberian-derived horses selected for survival and stock work in flooded grasslands.', tags: ['Island', 'Stock horse', 'Brazilian'], wiki: 'Marajoara', source: 'https://www.embrapa.br/en/busca-de-publicacoes/-/publicacao/409652/caracterizacao-genetica-de-equideos-da-raca-marajoara-por-microssatelites', relatedBreedIds: ['pantaneiro', 'criollo', 'mangalarga-marchador'], radiusKm: 280 },
  { id: 'medimurje', name: 'Međimurje Horse', location: 'Međimurje', country: 'Croatia', lat: 46.4, lng: 16.4, flag: '🇭🇷', coatColors: 'Bay, brown, black, chestnut, and roan.', hint: 'A very heavy lowland draft horse with a broad back, massive quarters, and calm nature.', fact: 'The Međimurje developed in the Mur–Drava river country from local mares and European heavy-horse influence; it is now critically endangered.', tags: ['Draft', 'Croatian', 'Critical'], wiki: 'Me%C4%91imurje_horse', relatedBreedIds: ['croatian-coldblood', 'nonius', 'ardennais'], radiusKm: 100 },
  { id: 'messara', name: 'Messara Horse', location: 'Messara Plain, Crete', country: 'Greece', lat: 35.05, lng: 24.8, flag: '🇬🇷', coatColors: 'Bay, brown, black, chestnut, and gray.', hint: 'A light Cretan riding horse noted for a smooth natural pacing gait.', fact: 'The rare Messara developed on Crete from local horses with historical Arabian influence and served transportation and light farm work.', tags: ['Gaited', 'Island', 'Greek'], wiki: 'Messara_horse', relatedBreedIds: ['arravani', 'arabian', 'pindos'], radiusKm: 100 },
  { id: 'murgese', name: 'Murgese', location: 'Murge, Apulia', country: 'Italy', lat: 40.9, lng: 17.2, flag: '🇮🇹', coatColors: 'Black or blue roan, with minimal white markings.', hint: 'A compact baroque Italian horse, usually jet black, with hard feet and a strong neck.', fact: 'The Murgese was re-established in Apulia from regional horses with Neapolitan, Arabian, and Barb ancestry for farm, military, and riding use.', tags: ['Baroque', 'Black coat', 'Italian'], wiki: 'Murgese', relatedBreedIds: ['friesian', 'san-fratellano', 'maremmano'], radiusKm: 170 },
  { id: 'mecklenburger', name: 'Mecklenburger', location: 'Mecklenburg-Vorpommern', country: 'Germany', lat: 53.7, lng: 12.5, flag: '🇩🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A refined northern sport horse selected for an uphill frame, elastic gaits, and jumping power.', fact: 'The Mecklenburger studbook traces to the state stud at Redefin and transformed a regional carriage and cavalry horse into a modern riding competitor.', tags: ['Warmblood', 'Sport horse', 'German'], wiki: 'Mecklenburger', relatedBreedIds: ['hanoverian', 'trakehner', 'oldenburg'], radiusKm: 220 },
  { id: 'nokota', name: 'Nokota Horse', location: 'Little Missouri Badlands', country: 'United States', lat: 47.0, lng: -103.5, flag: '🇺🇸', coatColors: 'Blue roan is iconic; black, gray, bay, chestnut, and overo also occur.', hint: 'A rugged western horse frequently seen in blue roan, with a strong square frame and hard feet.', fact: 'Nokotas descend from ranch and Native-associated horses that survived in North Dakota’s badlands and were later preserved outside Theodore Roosevelt National Park.', tags: ['Feral ancestry', 'Roan', 'American'], wiki: 'Nokota_horse', relatedBreedIds: ['mustang', 'spanish-mustang', 'appaloosa'], radiusKm: 320 },
  { id: 'north-swedish', name: 'North Swedish Horse', location: 'Northern Sweden', country: 'Sweden', lat: 62.5, lng: 16.5, flag: '🇸🇪', coatColors: 'Bay, brown, black, chestnut, and dun, sometimes with pangaré.', hint: 'A compact, energetic coldblood with excellent traction and endurance in forest terrain.', fact: 'The North Swedish Horse was standardized from northern farm stock with Døle influence for forestry, agriculture, and a separate trotting type.', tags: ['Coldblood', 'Forestry', 'Nordic'], wiki: 'North_Swedish_Horse', relatedBreedIds: ['dole-gudbrandsdal', 'finnhorse', 'fjord'], radiusKm: 660 },
  { id: 'oldenburg', name: 'Oldenburg', location: 'Oldenburg, Lower Saxony', country: 'Germany', lat: 53.1, lng: 8.2, flag: '🇩🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A large-framed German sport horse with powerful gaits and a generally expressive head.', fact: 'The Oldenburg began as a grand carriage horse fostered by Count Anton Günther and was transformed through open performance breeding into a modern sport horse.', tags: ['Warmblood', 'Sport horse', 'German'], wiki: 'Oldenburg_horse', relatedBreedIds: ['westphalian', 'holsteiner', 'hanoverian'], radiusKm: 180 },
  { id: 'pantaneiro', name: 'Pantaneiro Horse', location: 'Pantanal', country: 'Brazil', lat: -17.8, lng: -56.5, flag: '🇧🇷', coatColors: 'Bay, chestnut, brown, black, gray, dun, roan, and pinto.', hint: 'A tough cattle horse adapted to tropical heat, insects, marshes, and months of seasonal flooding.', fact: 'The Pantaneiro descends from Iberian horses that adapted for centuries to the vast Pantanal wetlands and remains essential to local ranching.', tags: ['Wetland', 'Stock horse', 'Brazilian'], wiki: 'Pantaneiro', relatedBreedIds: ['marajoara', 'criollo', 'mangalarga-marchador'], radiusKm: 720 },
  { id: 'brandenburger', name: 'Brandenburger', location: 'Brandenburg', country: 'Germany', lat: 52.4, lng: 13.0, flag: '🇩🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A balanced sport horse with a long-lined frame, energetic movement, and aptitude for jumping or dressage.', fact: 'Brandenburg breeders centered development around the Neustadt stud, using Trakehner, Hanoverian, and Thoroughbred influence to build a modern competition horse.', tags: ['Warmblood', 'Sport horse', 'German'], wiki: 'Brandenburger', relatedBreedIds: ['trakehner', 'hanoverian', 'mecklenburger'], radiusKm: 230 },
  { id: 'pindos', name: 'Pindos Pony', location: 'Pindus Mountains', country: 'Greece', lat: 39.7, lng: 21.2, flag: '🇬🇷', coatColors: 'Bay, brown, black, and gray, usually with little white.', hint: 'A narrow, tough pack pony with a coarse head, steep croup, and extremely hard feet.', fact: 'The Pindos is an ancient northern Greek mountain breed used for packing, forestry, farm work, and riding in steep terrain.', tags: ['Mountain pony', 'Pack horse', 'Greek'], wiki: 'Pindos_Pony', relatedBreedIds: ['messara', 'arravani', 'bosnian-mountain'], radiusKm: 240 },
  { id: 'pleven', name: 'Pleven Horse', location: 'Pleven region', country: 'Bulgaria', lat: 43.4, lng: 24.6, flag: '🇧🇬', coatColors: 'Chestnut is characteristic; bay and brown are less common.', hint: 'An elegant Anglo-Arabian-type saddle horse, usually chestnut, with lively but balanced movement.', fact: 'The Pleven was created at Klementina Stud from local, Anglo-Arabian, Arabian, and Thoroughbred stock for cavalry and sport.', tags: ['Saddle horse', 'Bulgarian', 'Anglo-Arabian'], wiki: 'Pleven_horse', relatedBreedIds: ['anglo-arabian', 'gidran', 'thoroughbred'], radiusKm: 180 },
  { id: 'posavac', name: 'Posavac Horse', location: 'Sava River basin', country: 'Croatia', lat: 45.4, lng: 16.7, flag: '🇭🇷', coatColors: 'Bay, brown, black, chestnut, and roan.', hint: 'A compact lowland coldblood with short strong legs and a broad, muscular body.', fact: 'The Posavac developed in the floodplain pastures of the Sava basin as an economical draft horse able to thrive outdoors on local forage.', tags: ['Coldblood', 'River lowland', 'Croatian'], wiki: 'Posavac_horse', relatedBreedIds: ['croatian-coldblood', 'medimurje', 'nonius'], radiusKm: 280 },
  { id: 'retuerta', name: 'Retuerta Horse', location: 'Doñana', country: 'Spain', lat: 37.0, lng: -6.4, flag: '🇪🇸', coatColors: 'Bay and dark bay, generally with very limited white.', hint: 'A lean, primitive feral horse with a convex profile and exceptionally hardy constitution.', fact: 'Retuerta horses have lived in the Doñana marshes for centuries and represent one of Europe’s oldest isolated horse populations.', tags: ['Feral', 'Primitive', 'Spanish'], wiki: 'Retuerta_horse', relatedBreedIds: ['sorraia', 'andalusian', 'marismeno'], radiusKm: 120 },
  { id: 'rhenish-german-coldblood', name: 'Rhenish German Coldblood', location: 'Rhineland', country: 'Germany', lat: 50.8, lng: 7.0, flag: '🇩🇪', coatColors: 'Chestnut and roan predominate; bay, brown, and black occur.', hint: 'A massive yet active German draft horse with a broad chest and powerful quarters.', fact: 'The Rhenish German Coldblood was built largely on Belgian draft ancestry for agriculture and heavy haulage in western Germany.', tags: ['Draft', 'German', 'Farm horse'], wiki: 'Rhenish_German_Coldblood', relatedBreedIds: ['belgian-draft', 'ardennais', 'south-german-coldblood'], radiusKm: 260 },
  { id: 'russian-heavy-draft', name: 'Russian Heavy Draft', location: 'European Russia', country: 'Russia', lat: 55.0, lng: 38.0, flag: '🇷🇺', coatColors: 'Chestnut and roan predominate; bay and brown occur.', hint: 'A relatively short, broad draft horse with immense pulling power and a lively walk.', fact: 'Russian breeders combined local mares with Ardennais and other European drafts to create an early-maturing, economical farm horse.', tags: ['Draft', 'Russian', 'Farm horse'], wiki: 'Russian_Heavy_Draft', relatedBreedIds: ['ardennais', 'soviet-heavy-draft', 'belarus-harness'], radiusKm: 800 },
  { id: 'sable-island-horse', name: 'Sable Island Horse', location: 'Sable Island', country: 'Canada', lat: 43.93, lng: -59.91, flag: '🇨🇦', coatColors: 'Bay and dark bay predominate; chestnut and black occur; gray and pinto are absent.', hint: 'A compact feral island horse with a shaggy winter coat and strong adaptation to sand and ocean weather.', fact: 'Sable Island Horses descend from animals placed on the remote Nova Scotian sandbar in the 1700s and are now protected as a naturalized population.', tags: ['Feral', 'Island', 'Canadian'], wiki: 'Sable_Island_horse', relatedBreedIds: ['canadian-horse', 'banker-horse', 'chincoteague-pony'], radiusKm: 85 },
  { id: 'sandalwood-pony', name: 'Sandalwood Pony', location: 'Sumba and Sumbawa', country: 'Indonesia', lat: -9.7, lng: 119.8, flag: '🇮🇩', coatColors: 'Bay, chestnut, brown, black, gray, dun, and pinto.', hint: 'A refined, heat-tolerant island pony with quick action and a reputation for racing.', fact: 'Also called the Sandalwood horse, this Indonesian breed combines local pony ancestry with historic Arabian influence and is central to Sumbanese riding culture.', tags: ['Island pony', 'Racing', 'Indonesian'], wiki: 'Sandalwood_Pony', relatedBreedIds: ['java-pony', 'batak-pony', 'arabian'], radiusKm: 350 },
  { id: 'san-fratellano', name: 'San Fratellano', location: 'Nebrodi Mountains, Sicily', country: 'Italy', lat: 38.0, lng: 14.6, flag: '🇮🇹', coatColors: 'Bay and black, with minimal white.', hint: 'A sturdy, dark Sicilian mountain horse with a strong frame and calm working character.', fact: 'The San Fratellano is a rare semi-feral breed of Sicily’s Nebrodi mountains, used for riding, pack work, and agricultural production.', tags: ['Mountain', 'Italian', 'Rare'], wiki: 'Sanfratellano', relatedBreedIds: ['murgese', 'catria', 'giara'], radiusKm: 130 },
  { id: 'sardinian-anglo-arab', name: 'Sardinian Anglo-Arab', location: 'Sardinia', country: 'Italy', lat: 40.1, lng: 9.0, flag: '🇮🇹', coatColors: 'Bay, chestnut, gray, brown, and black.', hint: 'A lean, energetic sport horse combining Sardinian hardiness with Thoroughbred and Arabian refinement.', fact: 'Sardinian breeders crossed island mares with Arabian and Thoroughbred stallions to produce an exceptional cavalry, racing, and eventing horse.', tags: ['Anglo-Arabian', 'Island', 'Sport horse'], wiki: 'Sardinian_Anglo-Arab', relatedBreedIds: ['anglo-arabian', 'arabian', 'thoroughbred'], radiusKm: 300 },
  { id: 'selle-francais', name: 'Selle Français', location: 'Normandy', country: 'France', lat: 49.0, lng: 0.0, flag: '🇫🇷', coatColors: 'Bay and chestnut predominate; brown, black, and gray occur.', hint: 'A powerful French sport horse renowned for scope, courage, and quick jumping reflexes.', fact: 'France unified its regional half-bred saddle populations under the Selle Français name in 1958, with Normandy remaining a major breeding center.', tags: ['Warmblood', 'Show jumping', 'French'], wiki: 'Selle_Fran%C3%A7ais', relatedBreedIds: ['anglo-arabian', 'belgian-warmblood', 'thoroughbred'], radiusKm: 280 },
  { id: 'senner', name: 'Senner', location: 'Senne, Teutoburg Forest', country: 'Germany', lat: 51.9, lng: 8.8, flag: '🇩🇪', coatColors: 'Bay, chestnut, gray, black, and occasional dun.', hint: 'A light, athletic German conservation breed with the hardiness of centuries of semi-feral management.', fact: 'The Senner is one of Germany’s oldest documented horse breeds and was kept in semi-wild herds by the Lippe princely house in the Senne.', tags: ['Historic', 'Semi-feral', 'German'], wiki: 'Senner', relatedBreedIds: ['trakehner', 'thoroughbred', 'konik'], radiusKm: 100 },
  { id: 'skyros-pony', name: 'Skyros Pony', location: 'Skyros', country: 'Greece', lat: 38.9, lng: 24.5, flag: '🇬🇷', coatColors: 'Bay, dark bay, brown, black, and gray; a dorsal stripe may occur.', hint: 'A tiny but horse-shaped island breed with a fine head, sloping shoulder, and tough feet.', fact: 'The endangered Skyros Pony has lived on its Aegean island for centuries and is genetically distinct from many northern European pony breeds.', tags: ['Island pony', 'Greek', 'Rare'], wiki: 'Skyros_Pony', relatedBreedIds: ['giara', 'shetland', 'pindos'], radiusKm: 75 },
  { id: 'sokolski', name: 'Sokólski Horse', location: 'Podlaskie', country: 'Poland', lat: 53.4, lng: 23.4, flag: '🇵🇱', coatColors: 'Chestnut, bay, roan, brown, and black.', hint: 'A compact Polish draft horse with a broad body, abundant muscle, and energetic movement.', fact: 'The Sokólski developed in northeastern Poland from local mares crossed with Ardennais and Breton-type stallions for strong but mobile farm work.', tags: ['Draft', 'Polish', 'Farm horse'], wiki: 'Sok%C3%B3lski_horse', relatedBreedIds: ['ardennais', 'breton', 'belarus-harness'], radiusKm: 260 },
  { id: 'south-german-coldblood', name: 'South German Coldblood', location: 'Bavaria', country: 'Germany', lat: 48.8, lng: 11.5, flag: '🇩🇪', coatColors: 'Chestnut with flaxen mane is common; bay, brown, black, and leopard spotting occur.', hint: 'A versatile medium-heavy draft horse closely related to the Noriker, often with a flaxen mane.', fact: 'The South German Coldblood developed from Noriker-type horses in Bavaria and remains valued for forestry, farming, and traditional driving.', tags: ['Draft', 'German', 'Forestry'], wiki: 'South_German_Coldblood', relatedBreedIds: ['noriker', 'rhenish-german-coldblood', 'black-forest'], radiusKm: 320 },
  { id: 'spanish-mustang', name: 'Spanish Mustang', location: 'American West', country: 'United States', lat: 37.0, lng: -106.0, flag: '🇺🇸', coatColors: 'Every solid color plus dun, roan, pinto, and leopard patterns.', hint: 'A small, tough colonial horse with a short back, sloping croup, and strong Spanish character.', fact: 'The Spanish Mustang is a conservation breed descended from Colonial Spanish horses maintained in isolated Native, ranch, and feral populations.', tags: ['Colonial Spanish', 'Endurance', 'American'], wiki: 'Spanish_Mustang', relatedBreedIds: ['mustang', 'kiger-mustang', 'florida-cracker'], radiusKm: 900 },
  { id: 'spiti-horse', name: 'Spiti Horse', location: 'Spiti and Kinnaur', country: 'India', lat: 31.9, lng: 78.3, flag: '🇮🇳', coatColors: 'Gray, bay, brown, black, chestnut, and dun.', hint: 'A compact Himalayan horse with dense bone, a thick coat, and extraordinary high-altitude sure-footedness.', fact: 'The Spiti is bred in Himachal Pradesh for pack and riding work across cold deserts and mountain passes where oxygen and forage are limited.', tags: ['Mountain', 'High altitude', 'Indian'], wiki: 'Spiti_Horse', relatedBreedIds: ['zaniskari', 'tibetan-pony', 'kyrgyz-horse'], radiusKm: 250 },
  { id: 'swiss-warmblood', name: 'Swiss Warmblood', location: 'Avenches and the Swiss Plateau', country: 'Switzerland', lat: 46.9, lng: 7.1, flag: '🇨🇭', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A capable modern riding horse with a harmonious frame, strong topline, and competition-minded movement.', fact: 'Also called the Swiss Sport Horse, this population was developed from Einsiedler mares and European warmblood lines under performance-focused selection.', tags: ['Warmblood', 'Sport horse', 'Versatile'], wiki: 'Swiss_Warmblood', relatedBreedIds: ['freiberger', 'hanoverian', 'holsteiner'], radiusKm: 260 },
  { id: 'tersk', name: 'Tersk Horse', location: 'Stavropol Krai', country: 'Russia', lat: 44.8, lng: 43.4, flag: '🇷🇺', coatColors: 'Gray predominates, often with a silvery sheen; bay and chestnut occur.', hint: 'A refined Russian riding horse resembling a substantial Arabian, usually light gray.', fact: 'The Tersk was created in the North Caucasus from surviving Strelets horses, Arabians, and related stock for military and sport use.', tags: ['Arabian type', 'Russian', 'Riding'], wiki: 'Tersk_horse', relatedBreedIds: ['arabian', 'shagya-arabian', 'kabarda'], radiusKm: 300 },
  { id: 'tibetan-pony', name: 'Tibetan Pony', location: 'Tibetan Plateau', country: 'China', lat: 31.5, lng: 88.0, flag: '🇨🇳', coatColors: 'Bay, brown, black, chestnut, gray, and dun.', hint: 'A small plateau horse with powerful lungs, hard feet, and a dense coat for cold, thin air.', fact: 'Tibetan ponies are traditional pack and riding horses of the high plateau, selected for survival and work at elevations challenging to most breeds.', tags: ['High altitude', 'Pack horse', 'Tibetan'], wiki: 'Tibetan_pony', relatedBreedIds: ['spiti-horse', 'zaniskari', 'mongolian'], radiusKm: 1000 },
  { id: 'trait-du-nord', name: 'Trait du Nord', location: 'Hainaut and northern France', country: 'France', lat: 50.3, lng: 3.4, flag: '🇫🇷', coatColors: 'Bay, roan, chestnut, brown, and black.', hint: 'A huge muscular draft horse with a short neck, broad chest, and relatively clean lower legs.', fact: 'The Trait du Nord developed in the Franco-Belgian industrial and farming region from Ardennais and Brabant-type horses for intense heavy work.', tags: ['Draft', 'French', 'Heavy horse'], wiki: 'Trait_du_Nord', relatedBreedIds: ['ardennais', 'belgian-draft', 'auxois'], radiusKm: 170 },
  { id: 'ukrainian-riding', name: 'Ukrainian Riding Horse', location: 'Ukraine', country: 'Ukraine', lat: 49.0, lng: 31.5, flag: '🇺🇦', coatColors: 'Bay, chestnut, brown, and black; gray is uncommon.', hint: 'A tall, elegant sport horse with a long neck, elastic gaits, and strong jumping ability.', fact: 'Ukrainian studs combined local and Hungarian mares with Thoroughbred, Hanoverian, and Trakehner blood to create a high-performance riding breed.', tags: ['Warmblood', 'Sport horse', 'Ukrainian'], wiki: 'Ukrainian_Riding_Horse', relatedBreedIds: ['trakehner', 'budyonny', 'furioso-north-star'], radiusKm: 720 },
  { id: 'swedish-warmblood', name: 'Swedish Warmblood', location: 'Southern Sweden', country: 'Sweden', lat: 56.9, lng: 14.2, flag: '🇸🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'An elegant Scandinavian sport horse prized for rideability, elastic gaits, and a powerful athletic build.', fact: 'Sweden transformed its cavalry and farm warmblood into an internationally successful dressage, jumping, and eventing horse through centralized testing and open sport breeding.', tags: ['Warmblood', 'Sport horse', 'Scandinavian'], wiki: 'Swedish_Warmblood', relatedBreedIds: ['danish-warmblood', 'hanoverian', 'trakehner'], radiusKm: 600 },
  { id: 'soviet-heavy-draft', name: 'Soviet Heavy Draft', location: 'Middle Volga and central Russia', country: 'Russia', lat: 55.4, lng: 45.5, flag: '🇷🇺', coatColors: 'Chestnut and flaxen chestnut predominate; bay and roan also occur.', hint: 'A massive, broad-bodied draft horse with a muscular neck, calm temperament, and notably efficient pulling strength.', fact: 'The Soviet Heavy Draft was developed from Belgian Brabant stallions and Russian mares, becoming an early-maturing agricultural and haulage horse recognized in 1952.', tags: ['Draft', 'Powerful', 'Farm horse'], wiki: 'Soviet_Heavy_Draft', relatedBreedIds: ['belgian-draft', 'russian-heavy-draft', 'ardennais'], radiusKm: 760 },
  { id: 'vyatka', name: 'Vyatka Horse', location: 'Kirov and Udmurtia', country: 'Russia', lat: 57.5, lng: 51.5, flag: '🇷🇺', coatColors: 'Dun, grullo, bay, brown, black, and chestnut, often with primitive markings.', hint: 'A compact northern forest horse with a dense coat, dark dorsal stripe, and energetic trot.', fact: 'The Vyatka is an old Finno-Ugric regional breed adapted to snow, forest travel, farm work, and limited winter forage.', tags: ['Forest horse', 'Finno-Ugric', 'Hardy'], wiki: 'Vyatka_horse', relatedBreedIds: ['finnhorse', 'estonian-native', 'bashkir-horse'], radiusKm: 620 },
  { id: 'westphalian', name: 'Westphalian', location: 'Westphalia', country: 'Germany', lat: 51.8, lng: 7.6, flag: '🇩🇪', coatColors: 'Bay, chestnut, brown, black, and gray.', hint: 'A large modern German sport horse with expressive gaits and a powerful jumping frame.', fact: 'Centered at Warendorf, the Westphalian studbook developed regional mares into a top dressage and jumping population through performance selection.', tags: ['Warmblood', 'Sport horse', 'German'], wiki: 'Westphalian_horse', relatedBreedIds: ['oldenburg', 'holsteiner', 'trakehner'], radiusKm: 220 },
  { id: 'yonaguni-horse', name: 'Yonaguni Horse', location: 'Yonaguni Island', country: 'Japan', lat: 24.46, lng: 123.0, flag: '🇯🇵', coatColors: 'Bay, dark bay, brown, and chestnut.', hint: 'A tiny, sturdy Japanese island horse with a large head, short legs, and calm nature.', fact: 'The Yonaguni is one of Japan’s eight native horse breeds and survives in small numbers on the country’s westernmost inhabited island.', tags: ['Japanese native', 'Island', 'Rare'], wiki: 'Yonaguni_horse', relatedBreedIds: ['noma-horse', 'kiso-horse', 'mongolian'], radiusKm: 75 },
  { id: 'zaniskari', name: 'Zaniskari', location: 'Zanskar, Ladakh', country: 'India', lat: 33.5, lng: 76.9, flag: '🇮🇳', coatColors: 'Gray, bay, brown, black, and chestnut.', hint: 'A compact Himalayan pack horse with great lung capacity and confidence on ice and rock.', fact: 'The Zaniskari is a rare high-altitude breed of Ladakh used for riding and loads across the cold, arid Zanskar mountains.', tags: ['High altitude', 'Pack horse', 'Indian'], wiki: 'Zaniskari', relatedBreedIds: ['spiti-horse', 'tibetan-pony', 'kyrgyz-horse'], radiusKm: 240 },
]

const wikiUrl = (slug: string) => `https://en.wikipedia.org/wiki/${slug}`
const localPhoto = (id: string, index: number) => `/horses/expansion/${id}-${index}.jpg`
const geographyWords = /\b(?:American|Austrian|Australian|Baltic|Belgian|Brazilian|British|Bulgarian|Caucasian|Central Asian|Chilean|Colonial Spanish|Croatian|Czech|Danish|Dutch|English|Estonian|European|French|German|Greek|Himalayan|Iberian|Indian|Indonesian|Irish|Italian|Japanese|Mexican|New Zealand|Nordic|Norwegian|Polish|Portuguese|Russian|Senegalese|South African|Spanish|Swedish|Swiss|Tibetan|Turkmen|Ukrainian)\b/gi
const geographyFreeHint = (hint: string) => hint.replace(geographyWords, '').replace(/\s{2,}/g, ' ').replace(/\s+,/g, ',').trim()

export const expansionBreeds: BreedSeed[] = records.map(record => ({
  id: record.id,
  name: record.name,
  image: localPhoto(record.id, 1),
  imageSource: expansionPhotoSources[record.id]?.[0] ?? `https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=${encodeURIComponent(record.name)}`,
  location: record.location,
  country: record.country,
  lat: record.lat,
  lng: record.lng,
  hint: geographyFreeHint(record.hint),
  fact: record.fact,
  tags: record.tags,
  source: record.source ?? wikiUrl(record.wiki),
}))

export const expansionProfiles: Record<string, BreedProfile> = Object.fromEntries(records.map(record => [record.id, {
  flag: record.flag,
  coatColors: record.coatColors,
  relatedBreedIds: record.relatedBreedIds,
}]))

export const expansionZoneSeeds = Object.fromEntries(records.map(record => [record.id, {
  label: record.location,
  note: `The full-score area generously covers ${record.location}, the breed’s documented homeland, rather than requiring one exact town or stud.`,
  center: { lat: record.lat, lng: record.lng },
  radiusKm: record.radiusKm,
  source: record.source ?? wikiUrl(record.wiki),
}]))

export const expansionBreedIds = records.map(record => record.id)
