// Generated by scripts/fetch-expansion-photos.mjs from verified Wikimedia Commons files.
import type { BreedPhoto } from './media'

export const expansionPhotoSources: Record<string, string[]> = {
  "american-miniature": [
    "https://commons.wikimedia.org/wiki/File%3AMiniature_horse_at_Amarillo_Zoo(3290197347).jpg",
    "https://commons.wikimedia.org/wiki/File%3AMiniature_Horse2.jpg"
  ],
  "anglo-arabian": [
    "https://commons.wikimedia.org/wiki/File%3AEtalon_Anglo-arabe.JPG",
    "https://commons.wikimedia.org/wiki/File%3AAnglo-arabian.jpg"
  ],
  "australian-draught": [
    "https://commons.wikimedia.org/wiki/File%3AAust_Draught_Horses.JPG"
  ],
  "abtenauer": [
    "https://commons.wikimedia.org/wiki/File%3ANoriker_horse_in_Salzburg_(state)_3336.jpg"
  ],
  "aegidienberger": [
    "https://commons.wikimedia.org/wiki/File%3AAegidienberger.jpg",
    "https://commons.wikimedia.org/wiki/File%3AAegidienberger_(Horse).jpg",
    "https://commons.wikimedia.org/wiki/File%3AAegidienberger2.jpg"
  ],
  "altai-horse": [
    "https://commons.wikimedia.org/wiki/File%3AHorse_Altai_01.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHorse_Altai_02.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHorse_Altai_05.jpg"
  ],
  "alter-real": [
    "https://commons.wikimedia.org/wiki/File%3ALusitano_stallion1.jpg",
    "https://commons.wikimedia.org/wiki/File%3AAlter_Real_(2).jpg",
    "https://commons.wikimedia.org/wiki/File%3AAlter_Real_au_travail_(2).jpg"
  ],
  "anglo-kabarda": [
    "https://commons.wikimedia.org/wiki/File%3AAngloKabardiner.jpg"
  ],
  "arravani": [
    "https://commons.wikimedia.org/wiki/File%3AArravani-Stuten.jpg"
  ],
  "auvergne-horse": [
    "https://www.sfet.fr/les-races/3-chevaux-poneys-de-territoire/15-le-cheval-de-race-auvergne",
    "https://commons.wikimedia.org/wiki/File%3ACheval-d-auvergneSDA2012.JPG",
    "https://commons.wikimedia.org/wiki/File%3ANemo-auvergnat-1.jpg"
  ],
  "auxois": [
    "https://commons.wikimedia.org/wiki/File%3AHorse_and_hay_bale%2C_Auxois_horse%2C_Burgundy%2C_France._flip-crop2.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHorse_and_hay_bale%2C_Auxois_horse%2C_Burgundy%2C_France._flip-crop1.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACheval_de_trait_auxois_SIA.jpg"
  ],
  "banker-horse": [
    "https://commons.wikimedia.org/wiki/File%3ASpanishMustangsOfCorolla.jpg",
    "https://commons.wikimedia.org/wiki/File%3A3_Banker_horses.jpg"
  ],
  "basotho-pony": [
    "https://www.claytor.com/photographs/"
  ],
  "batak-pony": [
    "https://creatures.com/species/horse/batak-pony"
  ],
  "belgian-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3ACHI_Gen%C3%A8ve_2013_-_20131213_-_Janika_Sprunger_et_Electra_Van't_Roosaker.jpg",
    "https://commons.wikimedia.org/wiki/File%3ABelgian_warmblood_whitni_star.JPG",
    "https://commons.wikimedia.org/wiki/File%3ABelgian_Warmblood.jpg"
  ],
  "kaimanawa": [
    "https://commons.wikimedia.org/wiki/File%3ASpirits_Bay_-_Wild_horses_New_Zealand.jpg"
  ],
  "bosnian-mountain": [
    "https://commons.wikimedia.org/wiki/File%3ABosanski_brdski_konj_pastuh_(cropped)_2.jpg",
    "https://zooclub.ru/loshadi/porody-loshadey/bosniyskaya-gornaya-loshad-bosniyskiy-poni.shtml"
  ],
  "budyonny": [
    "https://commons.wikimedia.org/wiki/File%3A%D0%91%D1%80%D1%83%D1%87.jpg",
    "https://commons.wikimedia.org/wiki/File%3ATwo_year_old_budjonny_stallions_in_russia.jpg"
  ],
  "burguete": [
    "https://commons.wikimedia.org/wiki/File%3AAuritzeko_zaldia_arra.JPG"
  ],
  "belarus-harness": [
    "https://commons.wikimedia.org/wiki/File%3ABelarusian_Harness_Horse_(cropped).jpg",
    "https://commons.wikimedia.org/wiki/File%3ABelarus_Harness_Horse_Orlik_I.jpg",
    "https://commons.wikimedia.org/wiki/File%3AAstra%2C_Belarusian_harness_horse_2.jpg"
  ],
  "freiberger": [
    "https://commons.wikimedia.org/wiki/File%3ASwiss_national_stud_farm_Avenches-IMG_8518_(cropped).jpg"
  ],
  "carolina-marsh-tacky": [
    "https://commons.wikimedia.org/wiki/File%3ACarolina_Marsh_Tacky.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACarolina_Marsh_Tacky_Horses_at_the_Lowcountry_Zoo_01.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACarolina_Marsh_Tacky2.jpg"
  ],
  "catria": [
    "https://www.repubblica.it/dossier/cronaca/la-repubblica-dei-cavalli/2022/04/15/news/cavallo_catria_marche-345637896/"
  ],
  "chincoteague-pony": [
    "https://commons.wikimedia.org/wiki/File%3AWild_Pony_at_Assateague.jpg",
    "https://commons.wikimedia.org/wiki/File%3A66_365_Chincoteague_Pony_-_Equus_ferus_caballus%2C_Assateague_National_Seashore%2C_Berlin%2C_Maryland%2C_March_7%2C_2021_(51014834021).jpg",
    "https://commons.wikimedia.org/wiki/File%3AChincoteague_pony%2C_Chincoteague_National_Wildlife_Refuge%2C_Chincoteague%2C_Virginia_(38415527881).jpg"
  ],
  "chilean-horse": [
    "https://commons.wikimedia.org/wiki/File%3AQuinchao_%E2%80%93_caballos_cerca_la_carretera_W-589%2C_2019.jpg"
  ],
  "irish-sport-horse": [
    "https://commons.wikimedia.org/wiki/File%3AIrish_Sport_Horse_foal_and_mare.jpg",
    "https://commons.wikimedia.org/wiki/File%3AIrish_Sport_Horse_-_Assagart_Lord_Lancer_standing.jpg",
    "https://commons.wikimedia.org/wiki/File%3AIrish_Sport_Horse_-_Assagart_Lord_Lancer.jpg"
  ],
  "corsican-horse": [
    "https://creatures.com/species/horse/corsican-horse",
    "https://commons.wikimedia.org/wiki/File%3ACumpagnu.jpg"
  ],
  "croatian-coldblood": [
    "https://commons.wikimedia.org/wiki/File%3AHrvatski_hladnokrvnjak.jpg"
  ],
  "dole-gudbrandsdal": [
    "https://commons.wikimedia.org/wiki/File%3ADole_eating_grass.jpg"
  ],
  "danish-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3AD%C3%A1nsk%C3%BD_k%C5%AF%C5%88.jpg"
  ],
  "misaki-horse": [
    "https://commons.wikimedia.org/wiki/File%3AMisaki_uma_May_2014_5419_(cropped).jpg"
  ],
  "dutch-harness": [
    "https://commons.wikimedia.org/wiki/File%3ADutchharnesshorse.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACoenraad_trained_by_Stal_Huisman%2C_Dutch_harness_horse%2C_Tuigpaard.jpg",
    "https://commons.wikimedia.org/wiki/File%3ADutch_Harness_stallion_01.jpg"
  ],
  "dutch-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3AUbility.jpg"
  ],
  "tori-horse": [
    "https://commons.wikimedia.org/wiki/File%3ATori_horse_universal.jpg",
    "https://commons.wikimedia.org/wiki/File%3ATori_sport_horse_copy.jpg",
    "https://commons.wikimedia.org/wiki/File%3ATori_horse_sport.jpg"
  ],
  "estonian-native": [
    "https://commons.wikimedia.org/wiki/File%3AEstonian_native_horse.jpg"
  ],
  "faroe-pony": [
    "https://commons.wikimedia.org/wiki/File%3AViking_horse_-_Isole_Faroe_-_panoramio.jpg",
    "https://commons.wikimedia.org/wiki/File%3AGrani.jpg",
    "https://commons.wikimedia.org/wiki/File%3AFaroe_pony_in_Hvalv%C3%ADk.jpg"
  ],
  "frederiksborg": [
    "https://commons.wikimedia.org/wiki/File%3AFrederiksborghest.jpg",
    "https://dyreportal.dk/koeb-heste/frederiksborg"
  ],
  "marismeno": [
    "https://commons.wikimedia.org/wiki/File%3ASaca_de_las_Yeguas_(14587429275).jpg"
  ],
  "galiceno": [
    "https://commons.wikimedia.org/wiki/File%3AGalice%C3%B1o_Horse%2C_%22Diosa_de_Oro%22.jpg"
  ],
  "gelderlander": [
    "https://commons.wikimedia.org/wiki/File%3AGelderlander_Viersp%C3%A4nner.jpg",
    "https://www.horsebreedspictures.com/gelderland-horse.asp"
  ],
  "groningen": [
    "https://www.bokt.nl/wiki/Bestand:OrbaldoII.jpg"
  ],
  "hackney-horse": [
    "https://commons.wikimedia.org/wiki/File%3AHackney_Horse_Stallion_CANADANCE.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHackney_horse.jpg",
    "https://commons.wikimedia.org/wiki/File%3AMum_And_Daughter_(2899216285).jpg"
  ],
  "henson-horse": [
    "https://commons.wikimedia.org/wiki/File%3ACheval_henson.JPG",
    "https://commons.wikimedia.org/wiki/File%3AHenson_horses_parc_du_marqueterre.jpg",
    "https://commons.wikimedia.org/wiki/File%3AChevaux_Henson%2C_typiques_de_la_Baie_d'Authie.jpg"
  ],
  "hispano-breton": [
    "https://commons.wikimedia.org/wiki/File%3AAns%C3%B3_1993_13_(cropped).jpg"
  ],
  "holsteiner": [
    "https://commons.wikimedia.org/wiki/File%3AHolsteiner_Apfelschimmel-2005.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHolsteiner_0001.jpg"
  ],
  "hanoverian": [
    "https://commons.wikimedia.org/wiki/File%3ALantinus_and_Lynch.jpg",
    "https://www.ehorses.com/hanoverian-mare-6years-162-hh-brown-dressagehorses-langelsheim/4244395.html",
    "https://portret-konia.blogspot.com/2013/03/kon-hanowerski.html"
  ],
  "iomud": [
    "https://horse.xjau.edu.cn/breeds/list/99"
  ],
  "jaca-navarra": [
    "https://commons.wikimedia.org/wiki/File%3ANafar_behoka_zaldia1.JPG",
    "https://commons.wikimedia.org/wiki/File%3AEntrega_de_Premios_jaca_navarra_2022_(Estella%2C_Navarra).jpg"
  ],
  "java-pony": [
    "https://commons.wikimedia.org/wiki/File%3ABromo-Tengger-Semeru-National-Park_Indonesia_Horses-02.jpg",
    "https://commons.wikimedia.org/wiki/File%3AJava_Pony.jpg",
    "https://commons.wikimedia.org/wiki/File%3APony%2C_Mount_Bromo_(Gunung_Bromo)_Indonesia%2C_East_Java.jpg"
  ],
  "kabarda": [
    "https://commons.wikimedia.org/wiki/File%3AIMG-20200516-WA0002.jpg"
  ],
  "karabair": [
    "https://commons.wikimedia.org/wiki/File%3AKarabair_-_C%C3%A9sar_Augusto_Gonz%C3%A1lez_(2017).jpg"
  ],
  "karachay": [
    "https://commons.wikimedia.org/wiki/File%3A%D0%A1%D1%83%D1%80%D0%B0%D1%82_%D0%A1%D0%B5%D1%80%D0%B1%D0%B0%D0%B7%D1%8B%D1%87.jpg",
    "https://commons.wikimedia.org/wiki/File%3AKarachay_horse_breeds.JPG"
  ],
  "kiger-mustang": [
    "https://commons.wikimedia.org/wiki/File%3AMesteno.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASorraia_phenotype_in_the_Kiger_Mustang_mare_Ciente.jpg",
    "https://commons.wikimedia.org/wiki/File%3AKiger_Mustang_stallions.jpg"
  ],
  "kinsky-horse": [
    "https://commons.wikimedia.org/wiki/File%3AJerome_Kinsky_Zlosyn_2005.jpg"
  ],
  "kiso-horse": [
    "https://commons.wikimedia.org/wiki/File%3A%E6%9C%A8%E6%9B%BD%E9%A7%92_1.jpg"
  ],
  "kyrgyz-horse": [
    "https://commons.wikimedia.org/wiki/File%3AMare_milking_Suusamyr.jpg",
    "https://commons.wikimedia.org/wiki/File%3AKyrgyz_horses%2C_Kyrgyz_people_like_to_drink_milk_and_make_a_kymyz!.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHorse_standing_by_Song_Kul_Lake_-_Kyrgyztan.jpg"
  ],
  "latvian-horse": [
    "https://commons.wikimedia.org/wiki/File%3ALettwarmblut.jpg",
    "https://commons.wikimedia.org/wiki/File%3AHorses_Latvian_EM.JPG"
  ],
  "bavarian-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3ABavarian_Warmblood.jpg"
  ],
  "losino": [
    "https://commons.wikimedia.org/wiki/File%3ACaballos_losinos_(30_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1)_10.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACaballos_losinos_(30_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1)_02.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACaballos_losinos_(30_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1)_09.jpg"
  ],
  "malopolski": [
    "https://commons.wikimedia.org/wiki/File%3AKo%C5%84_ma%C5%82opolski.JPG"
  ],
  "mangalarga-paulista": [
    "https://commons.wikimedia.org/wiki/File%3AColorado_rn_Mangalarga_Paulista.jpg",
    "https://commons.wikimedia.org/wiki/File%3AMangalarga_Paulista.jpg"
  ],
  "manipuri-pony": [
    "https://indianexpress.com/article/north-east-india/manipur/manipur-why-the-worlds-original-polo-pony-is-dying/"
  ],
  "marajoara": [
    "https://commons.wikimedia.org/wiki/File:Salvaterra,_Par%C3%A1,_Brasil_-_2013.10.15_(10).jpg"
  ],
  "medimurje": [
    "https://commons.wikimedia.org/wiki/File%3AMe%C4%91imurski_konj_(Croatia)_-_pastuh.jpg"
  ],
  "messara": [
    "https://commons.wikimedia.org/wiki/File%3ACheval_cr%C3%A9tois_profil.jpg"
  ],
  "murgese": [
    "https://commons.wikimedia.org/wiki/File%3AMurgese_Donato.jpg",
    "https://commons.wikimedia.org/wiki/File%3ACavallo_Murgese_Troiano_ed_Inama_Roberta%2C_gara_di_Dressage.JPG",
    "https://commons.wikimedia.org/wiki/File%3AMurgese2.jpg"
  ],
  "mecklenburger": [
    "https://commons.wikimedia.org/wiki/File%3AMecklenburger_Warmblut_(Marienfelde).JPG"
  ],
  "nokota": [
    "https://commons.wikimedia.org/wiki/File%3ANokota_Horses_cropped.jpg",
    "https://commons.wikimedia.org/wiki/File%3ANokota_Horse_Stud_Band.jpg",
    "https://commons.wikimedia.org/wiki/File%3ANokota_Horses.jpg"
  ],
  "north-swedish": [
    "https://nordensark.se/djuren/lantraser/nordsvensk-hast/",
    "https://commons.wikimedia.org/wiki/File%3ANorth_swedish_horse_ugglan.jpg"
  ],
  "oldenburg": [
    "https://commons.wikimedia.org/wiki/File%3ABess2.jpg"
  ],
  "pantaneiro": [
    "https://commons.wikimedia.org/wiki/File%3ABoiada_sendo_conduzida_pelos_pantaneiros.jpg"
  ],
  "brandenburger": [
    "https://commons.wikimedia.org/wiki/File%3AWilliam_FOX-PITT_JEM2014_crop.jpg"
  ],
  "pindos": [
    "https://commons.wikimedia.org/wiki/File%3AKOYNIS_XRISTOS.jpg"
  ],
  "pleven": [
    "https://commons.wikimedia.org/wiki/File%3APleven_horse_10.jpg",
    "https://commons.wikimedia.org/wiki/File%3APleven_horse_4.jpg",
    "https://commons.wikimedia.org/wiki/File%3APleven_horse_1.jpg"
  ],
  "posavac": [
    "https://commons.wikimedia.org/wiki/File%3AHrvatski_posavac.JPG"
  ],
  "retuerta": [
    "https://commons.wikimedia.org/wiki/File%3ACaballos_en_Do%C3%B1ana_-_panoramio.jpg"
  ],
  "rhenish-german-coldblood": [
    "https://commons.wikimedia.org/wiki/File%3AWillowRDK_(cropped).jpg"
  ],
  "russian-heavy-draft": [
    "https://www.ruhorses.ru/breed/russian_heavy/en"
  ],
  "sable-island-horse": [
    "https://commons.wikimedia.org/wiki/File%3ASableHorses2.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASable_Island_Horse.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASable_Island_Horses.jpg"
  ],
  "sandalwood-pony": [
    "https://commons.wikimedia.org/wiki/File%3ASdldrgm.jpg"
  ],
  "san-fratellano": [
    "https://www.agraria.org/equini/sanfratellano.htm"
  ],
  "sardinian-anglo-arab": [
    "https://commons.wikimedia.org/wiki/File%3ALavinpiano_(cropped_less).JPG"
  ],
  "selle-francais": [
    "https://commons.wikimedia.org/wiki/File%3ACheval_selle.JPG",
    "https://commons.wikimedia.org/wiki/File%3ASelle_Fran%C3%A7ais.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASelle_fran%C3%A7ais_t%C3%AAte2.jpg"
  ],
  "senner": [
    "https://commons.wikimedia.org/wiki/File%3AStukenbrock_Senner_Pferde_Moosheide_078%2C_cropped.jpg",
    "https://commons.wikimedia.org/wiki/File%3AStukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_(047).jpg",
    "https://commons.wikimedia.org/wiki/File%3AStukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_(035).jpg"
  ],
  "skyros-pony": [
    "https://commons.wikimedia.org/wiki/File%3AThe_Skyros_pony.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASkyros_horse.jpg",
    "https://commons.wikimedia.org/wiki/File%3AMule_and_Skyros_ponies.jpg"
  ],
  "sokolski": [
    "https://commons.wikimedia.org/wiki/File%3AJarmark_%E2%80%93_ko%C5%84_-_Sok%C3%B3%C5%82ka_-_000723s_(cropped).jpg"
  ],
  "south-german-coldblood": [
    "https://commons.wikimedia.org/wiki/File%3AS%C3%BCddeutsches_Kaltblut_3_(cropped).jpg"
  ],
  "spanish-mustang": [
    "https://commons.wikimedia.org/wiki/File%3AGypsypasturepic1.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASpanishMustang.jpg"
  ],
  "spiti-horse": [
    "https://commons.wikimedia.org/wiki/File%3ACarrier_Horse_of_Gaddi_community_in_Kasauli_%2C_Himachal_Pardes%2C_India.JPG",
    "https://commons.wikimedia.org/wiki/File%3AHorses_near_Langza%2C_Spiti_Valley%2C_Himachal_Pradesh%2C_India.jpg"
  ],
  "swiss-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3A54eme_CHI_de_Gen%C3%A8ve%2C_Prix_de_la_F%C3%A9d%C3%A9ration_d%E2%80%99Elevage_du_Cheval_de_Sport_CH%2C_P%C3%A9n%C3%A9lope_Leprevost_et_Cayman_Athletic_CH_3_(cropped).jpg"
  ],
  "tersk": [
    "https://commons.wikimedia.org/wiki/File%3ABasilick_tersk.jpg",
    "https://rahba.org/ru/horse/9405"
  ],
  "tibetan-pony": [
    "https://commons.wikimedia.org/wiki/File%3ATibetHorse2.jpg",
    "https://commons.wikimedia.org/wiki/File%3ATibetan_Nomad_with_black_horse%2C_Gansu%2C_China.jpg",
    "https://commons.wikimedia.org/wiki/File%3ATibetan_horses_below_Chomo_Lhari%2C_Tibet_in_1938_from_Bundesarchiv_Bild_135-S-10-04-32%2C_Tibetexpedition%2C_Karawane_vor_Chomolhari_(cropped).jpg"
  ],
  "trait-du-nord": [
    "https://commons.wikimedia.org/wiki/File%3ATrait-du-nord01_SDA2012.JPG",
    "https://commons.wikimedia.org/wiki/File%3ATrait-du-nord02_SDA2012.JPG",
    "https://commons.wikimedia.org/wiki/File%3ATrait-du-nord03_SDA2012.JPG"
  ],
  "ukrainian-riding": [
    "https://commons.wikimedia.org/wiki/File%3A%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%B2%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%B0.jpg"
  ],
  "swedish-warmblood": [
    "https://commons.wikimedia.org/wiki/File%3A2018FEI-WORLD-CUP-DRESSAGE-Patrik-Kittel_(cropped).jpg"
  ],
  "soviet-heavy-draft": [
    "https://commons.wikimedia.org/wiki/File%3ASoviet_heavy_draft.jpg",
    "https://commons.wikimedia.org/wiki/File%3ASoviet_Heavy_Draft._Sevastopol_Zoo..JPG"
  ],
  "vyatka": [
    "https://commons.wikimedia.org/wiki/File%3AVyatka_horse.jpg",
    "https://commons.wikimedia.org/wiki/File%3AVyatka_Gelding_1899.jpg"
  ],
  "westphalian": [
    "https://commons.wikimedia.org/wiki/File%3AAvenger_-_Westphalian_horse.jpg"
  ],
  "yonaguni-horse": [
    "https://commons.wikimedia.org/wiki/File%3AYonaguni_horse_3_(cropped).jpg",
    "https://commons.wikimedia.org/wiki/File%3AYonaguni_Horse_%40_Rokkosan_Pasture.jpg",
    "https://commons.wikimedia.org/wiki/File%3AYonaguni_horse_5.jpg"
  ],
  "zaniskari": [
    "https://commons.wikimedia.org/wiki/File%3A08IN1912_horse_and_Gamburanjun.jpg"
  ]
}

const expansionPhotoUrls: Record<string, string[]> = {
  "american-miniature": [
    "/horses/expansion/american-miniature-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Miniature_Horse2.jpg/330px-Miniature_Horse2.jpg"
  ],
  "anglo-arabian": [
    "/horses/expansion/anglo-arabian-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Anglo-arabian.jpg/500px-Anglo-arabian.jpg"
  ],
  "australian-draught": [
    "/horses/expansion/australian-draught-1.jpg"
  ],
  "abtenauer": [
    "/horses/expansion/abtenauer-1.jpg"
  ],
  "aegidienberger": [
    "/horses/expansion/aegidienberger-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Aegidienberger_%28Horse%29.jpg/500px-Aegidienberger_%28Horse%29.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Aegidienberger2.jpg/330px-Aegidienberger2.jpg"
  ],
  "altai-horse": [
    "/horses/expansion/altai-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Horse_Altai_02.jpg/500px-Horse_Altai_02.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Horse_Altai_05.jpg/500px-Horse_Altai_05.jpg"
  ],
  "alter-real": [
    "/horses/expansion/alter-real-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Alter_Real_%282%29.jpg/500px-Alter_Real_%282%29.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Alter_Real_au_travail_%282%29.jpg/500px-Alter_Real_au_travail_%282%29.jpg"
  ],
  "anglo-kabarda": [
    "/horses/expansion/anglo-kabarda-1.jpg"
  ],
  "arravani": [
    "/horses/expansion/arravani-1.jpg"
  ],
  "auvergne-horse": [
    "/horses/expansion/auvergne-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Cheval-d-auvergneSDA2012.JPG/500px-Cheval-d-auvergneSDA2012.JPG",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Nemo-auvergnat-1.jpg/330px-Nemo-auvergnat-1.jpg"
  ],
  "auxois": [
    "/horses/expansion/auxois-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Horse_and_hay_bale%2C_Auxois_horse%2C_Burgundy%2C_France._flip-crop1.jpg/500px-Horse_and_hay_bale%2C_Auxois_horse%2C_Burgundy%2C_France._flip-crop1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Cheval_de_trait_auxois_SIA.jpg/330px-Cheval_de_trait_auxois_SIA.jpg"
  ],
  "banker-horse": [
    "/horses/expansion/banker-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/3_Banker_horses.jpg/500px-3_Banker_horses.jpg"
  ],
  "basotho-pony": [
    "/horses/expansion/basotho-pony-1.jpg"
  ],
  "batak-pony": [
    "/horses/expansion/batak-pony-1.jpg"
  ],
  "belgian-warmblood": [
    "/horses/expansion/belgian-warmblood-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Belgian_warmblood_whitni_star.JPG/500px-Belgian_warmblood_whitni_star.JPG",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Belgian_Warmblood.jpg/960px-Belgian_Warmblood.jpg"
  ],
  "kaimanawa": [
    "/horses/expansion/kaimanawa-1.jpg"
  ],
  "bosnian-mountain": [
    "/horses/expansion/bosnian-mountain-1.jpg",
    "/horses/expansion/bosnian-mountain-2.jpg"
  ],
  "budyonny": [
    "/horses/expansion/budyonny-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Two_year_old_budjonny_stallions_in_russia.jpg/330px-Two_year_old_budjonny_stallions_in_russia.jpg"
  ],
  "burguete": [
    "/horses/expansion/burguete-1.jpg"
  ],
  "belarus-harness": [
    "/horses/expansion/belarus-harness-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Belarus_Harness_Horse_Orlik_I.jpg/250px-Belarus_Harness_Horse_Orlik_I.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Astra%2C_Belarusian_harness_horse_2.jpg/500px-Astra%2C_Belarusian_harness_horse_2.jpg"
  ],
  "freiberger": [
    "/horses/expansion/freiberger-1.jpg"
  ],
  "carolina-marsh-tacky": [
    "/horses/expansion/carolina-marsh-tacky-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Carolina_Marsh_Tacky_Horses_at_the_Lowcountry_Zoo_01.jpg/960px-Carolina_Marsh_Tacky_Horses_at_the_Lowcountry_Zoo_01.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Carolina_Marsh_Tacky2.jpg/330px-Carolina_Marsh_Tacky2.jpg"
  ],
  "catria": [
    "/horses/expansion/catria-1.jpg"
  ],
  "chincoteague-pony": [
    "/horses/expansion/chincoteague-pony-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/66_365_Chincoteague_Pony_-_Equus_ferus_caballus%2C_Assateague_National_Seashore%2C_Berlin%2C_Maryland%2C_March_7%2C_2021_%2851014834021%29.jpg/960px-66_365_Chincoteague_Pony_-_Equus_ferus_caballus%2C_Assateague_National_Seashore%2C_Berlin%2C_Maryland%2C_March_7%2C_2021_%2851014834021%29.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Chincoteague_pony%2C_Chincoteague_National_Wildlife_Refuge%2C_Chincoteague%2C_Virginia_%2838415527881%29.jpg/960px-Chincoteague_pony%2C_Chincoteague_National_Wildlife_Refuge%2C_Chincoteague%2C_Virginia_%2838415527881%29.jpg"
  ],
  "chilean-horse": [
    "/horses/expansion/chilean-horse-1.jpg"
  ],
  "irish-sport-horse": [
    "/horses/expansion/irish-sport-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Irish_Sport_Horse_-_Assagart_Lord_Lancer_standing.jpg/330px-Irish_Sport_Horse_-_Assagart_Lord_Lancer_standing.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Irish_Sport_Horse_-_Assagart_Lord_Lancer.jpg/330px-Irish_Sport_Horse_-_Assagart_Lord_Lancer.jpg"
  ],
  "corsican-horse": [
    "/horses/expansion/corsican-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Cumpagnu.jpg/500px-Cumpagnu.jpg"
  ],
  "croatian-coldblood": [
    "/horses/expansion/croatian-coldblood-1.jpg"
  ],
  "dole-gudbrandsdal": [
    "/horses/expansion/dole-gudbrandsdal-1.jpg"
  ],
  "danish-warmblood": [
    "/horses/expansion/danish-warmblood-1.jpg"
  ],
  "misaki-horse": [
    "/horses/expansion/misaki-horse-1.jpg"
  ],
  "dutch-harness": [
    "/horses/expansion/dutch-harness-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Coenraad_trained_by_Stal_Huisman%2C_Dutch_harness_horse%2C_Tuigpaard.jpg/330px-Coenraad_trained_by_Stal_Huisman%2C_Dutch_harness_horse%2C_Tuigpaard.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Dutch_Harness_stallion_01.jpg/500px-Dutch_Harness_stallion_01.jpg"
  ],
  "dutch-warmblood": [
    "/horses/expansion/dutch-warmblood-1.jpg"
  ],
  "tori-horse": [
    "/horses/expansion/tori-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Tori_sport_horse_copy.jpg/330px-Tori_sport_horse_copy.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Tori_horse_sport.jpg/250px-Tori_horse_sport.jpg"
  ],
  "estonian-native": [
    "/horses/expansion/estonian-native-1.jpg"
  ],
  "faroe-pony": [
    "/horses/expansion/faroe-pony-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Grani.jpg/330px-Grani.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Faroe_pony_in_Hvalv%C3%ADk.jpg/330px-Faroe_pony_in_Hvalv%C3%ADk.jpg"
  ],
  "frederiksborg": [
    "/horses/expansion/frederiksborg-1.jpg",
    "/horses/expansion/frederiksborg-2.jpg"
  ],
  "marismeno": [
    "/horses/expansion/marismeno-1.jpg"
  ],
  "galiceno": [
    "/horses/expansion/galiceno-1.jpg"
  ],
  "gelderlander": [
    "/horses/expansion/gelderlander-1.jpg",
    "/horses/expansion/gelderlander-2.jpg"
  ],
  "groningen": [
    "/horses/expansion/groningen-1.jpg"
  ],
  "hackney-horse": [
    "/horses/expansion/hackney-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Hackney_horse.jpg/330px-Hackney_horse.jpg",
    "/horses/expansion/hackney-horse-3.jpg"
  ],
  "henson-horse": [
    "/horses/expansion/henson-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Henson_horses_parc_du_marqueterre.jpg/960px-Henson_horses_parc_du_marqueterre.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Chevaux_Henson%2C_typiques_de_la_Baie_d%27Authie.jpg/500px-Chevaux_Henson%2C_typiques_de_la_Baie_d%27Authie.jpg"
  ],
  "hispano-breton": [
    "/horses/expansion/hispano-breton-1.jpg"
  ],
  "holsteiner": [
    "/horses/expansion/holsteiner-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Holsteiner_0001.jpg/500px-Holsteiner_0001.jpg"
  ],
  "hanoverian": [
    "/horses/expansion/hanoverian-1.jpg",
    "/horses/expansion/hanoverian-2.jpg",
    "/horses/expansion/hanoverian-3.jpg"
  ],
  "iomud": [
    "/horses/expansion/iomud-1.jpg"
  ],
  "jaca-navarra": [
    "/horses/expansion/jaca-navarra-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Entrega_de_Premios_jaca_navarra_2022_%28Estella%2C_Navarra%29.jpg/960px-Entrega_de_Premios_jaca_navarra_2022_%28Estella%2C_Navarra%29.jpg"
  ],
  "java-pony": [
    "/horses/expansion/java-pony-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Java_Pony.jpg/250px-Java_Pony.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Pony%2C_Mount_Bromo_%28Gunung_Bromo%29_Indonesia%2C_East_Java.jpg/960px-Pony%2C_Mount_Bromo_%28Gunung_Bromo%29_Indonesia%2C_East_Java.jpg"
  ],
  "kabarda": [
    "/horses/expansion/kabarda-1.jpg"
  ],
  "karabair": [
    "/horses/expansion/karabair-1.jpg"
  ],
  "karachay": [
    "/horses/expansion/karachay-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Karachay_horse_breeds.JPG/960px-Karachay_horse_breeds.JPG"
  ],
  "kiger-mustang": [
    "/horses/expansion/kiger-mustang-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Sorraia_phenotype_in_the_Kiger_Mustang_mare_Ciente.jpg/500px-Sorraia_phenotype_in_the_Kiger_Mustang_mare_Ciente.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Kiger_Mustang_stallions.jpg/330px-Kiger_Mustang_stallions.jpg"
  ],
  "kinsky-horse": [
    "/horses/expansion/kinsky-horse-1.jpg"
  ],
  "kiso-horse": [
    "/horses/expansion/kiso-horse-1.jpg"
  ],
  "kyrgyz-horse": [
    "/horses/expansion/kyrgyz-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Kyrgyz_horses%2C_Kyrgyz_people_like_to_drink_milk_and_make_a_kymyz%21.jpg/330px-Kyrgyz_horses%2C_Kyrgyz_people_like_to_drink_milk_and_make_a_kymyz%21.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Horse_standing_by_Song_Kul_Lake_-_Kyrgyztan.jpg/960px-Horse_standing_by_Song_Kul_Lake_-_Kyrgyztan.jpg"
  ],
  "latvian-horse": [
    "/horses/expansion/latvian-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Horses_Latvian_EM.JPG/500px-Horses_Latvian_EM.JPG"
  ],
  "bavarian-warmblood": [
    "/horses/expansion/bavarian-warmblood-1.jpg"
  ],
  "losino": [
    "/horses/expansion/losino-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Caballos_losinos_%2830_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1%29_02.jpg/960px-Caballos_losinos_%2830_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1%29_02.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Caballos_losinos_%2830_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1%29_09.jpg/960px-Caballos_losinos_%2830_de_abril_de_2018%2C_Reserva_y_Centro_de_Interpretaci%C3%B3n_del_Bisonte_Europeo_de_San_Cebri%C3%A1n_de_Mud%C3%A1%29_09.jpg"
  ],
  "malopolski": [
    "/horses/expansion/malopolski-1.jpg"
  ],
  "mangalarga-paulista": [
    "/horses/expansion/mangalarga-paulista-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Mangalarga_Paulista.jpg/500px-Mangalarga_Paulista.jpg"
  ],
  "manipuri-pony": [
    "/horses/expansion/manipuri-pony-1.jpg"
  ],
  "marajoara": [
    "/horses/expansion/marajoara-1.jpg"
  ],
  "medimurje": [
    "/horses/expansion/medimurje-1.jpg"
  ],
  "messara": [
    "/horses/expansion/messara-1.jpg"
  ],
  "murgese": [
    "/horses/expansion/murgese-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Cavallo_Murgese_Troiano_ed_Inama_Roberta%2C_gara_di_Dressage.JPG/500px-Cavallo_Murgese_Troiano_ed_Inama_Roberta%2C_gara_di_Dressage.JPG",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Murgese2.jpg/250px-Murgese2.jpg"
  ],
  "mecklenburger": [
    "/horses/expansion/mecklenburger-1.jpg"
  ],
  "nokota": [
    "/horses/expansion/nokota-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Nokota_Horse_Stud_Band.jpg/960px-Nokota_Horse_Stud_Band.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Nokota_Horses.jpg/500px-Nokota_Horses.jpg"
  ],
  "north-swedish": [
    "/horses/expansion/north-swedish-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/North_swedish_horse_ugglan.jpg/330px-North_swedish_horse_ugglan.jpg"
  ],
  "oldenburg": [
    "/horses/expansion/oldenburg-1.jpg"
  ],
  "pantaneiro": [
    "/horses/expansion/pantaneiro-1.jpg"
  ],
  "brandenburger": [
    "/horses/expansion/brandenburger-1.jpg"
  ],
  "pindos": [
    "/horses/expansion/pindos-1.jpg"
  ],
  "pleven": [
    "/horses/expansion/pleven-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Pleven_horse_4.jpg/500px-Pleven_horse_4.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Pleven_horse_1.jpg/500px-Pleven_horse_1.jpg"
  ],
  "posavac": [
    "/horses/expansion/posavac-1.jpg"
  ],
  "retuerta": [
    "/horses/expansion/retuerta-1.jpg"
  ],
  "rhenish-german-coldblood": [
    "/horses/expansion/rhenish-german-coldblood-1.jpg"
  ],
  "russian-heavy-draft": [
    "/horses/expansion/russian-heavy-draft-1.jpg"
  ],
  "sable-island-horse": [
    "/horses/expansion/sable-island-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Sable_Island_Horse.jpg/250px-Sable_Island_Horse.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Sable_Island_Horses.jpg/960px-Sable_Island_Horses.jpg"
  ],
  "sandalwood-pony": [
    "/horses/expansion/sandalwood-pony-1.jpg"
  ],
  "san-fratellano": [
    "/horses/expansion/san-fratellano-1.jpg"
  ],
  "sardinian-anglo-arab": [
    "/horses/expansion/sardinian-anglo-arab-1.jpg"
  ],
  "selle-francais": [
    "/horses/expansion/selle-francais-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Selle_Fran%C3%A7ais.jpg/500px-Selle_Fran%C3%A7ais.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Selle_fran%C3%A7ais_t%C3%AAte2.jpg/960px-Selle_fran%C3%A7ais_t%C3%AAte2.jpg"
  ],
  "senner": [
    "/horses/expansion/senner-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Stukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_%28047%29.jpg/960px-Stukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_%28047%29.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Stukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_%28035%29.jpg/960px-Stukenbrock_-_2016-05-01_-_Senner_Pferde_Moosheide_%28035%29.jpg"
  ],
  "skyros-pony": [
    "/horses/expansion/skyros-pony-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Skyros_horse.jpg/500px-Skyros_horse.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Mule_and_Skyros_ponies.jpg/330px-Mule_and_Skyros_ponies.jpg"
  ],
  "sokolski": [
    "/horses/expansion/sokolski-1.jpg"
  ],
  "south-german-coldblood": [
    "/horses/expansion/south-german-coldblood-1.jpg"
  ],
  "spanish-mustang": [
    "/horses/expansion/spanish-mustang-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/SpanishMustang.jpg/330px-SpanishMustang.jpg"
  ],
  "spiti-horse": [
    "/horses/expansion/spiti-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Horses_near_Langza%2C_Spiti_Valley%2C_Himachal_Pradesh%2C_India.jpg/250px-Horses_near_Langza%2C_Spiti_Valley%2C_Himachal_Pradesh%2C_India.jpg"
  ],
  "swiss-warmblood": [
    "/horses/expansion/swiss-warmblood-1.jpg"
  ],
  "tersk": [
    "/horses/expansion/tersk-1.jpg",
    "/horses/expansion/tersk-2.jpg"
  ],
  "tibetan-pony": [
    "/horses/expansion/tibetan-pony-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Tibetan_Nomad_with_black_horse%2C_Gansu%2C_China.jpg/960px-Tibetan_Nomad_with_black_horse%2C_Gansu%2C_China.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Tibetan_horses_below_Chomo_Lhari%2C_Tibet_in_1938_from_Bundesarchiv_Bild_135-S-10-04-32%2C_Tibetexpedition%2C_Karawane_vor_Chomolhari_%28cropped%29.jpg/330px-Tibetan_horses_below_Chomo_Lhari%2C_Tibet_in_1938_from_Bundesarchiv_Bild_135-S-10-04-32%2C_Tibetexpedition%2C_Karawane_vor_Chomolhari_%28cropped%29.jpg"
  ],
  "trait-du-nord": [
    "/horses/expansion/trait-du-nord-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Trait-du-nord02_SDA2012.JPG/500px-Trait-du-nord02_SDA2012.JPG",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Trait-du-nord03_SDA2012.JPG/330px-Trait-du-nord03_SDA2012.JPG"
  ],
  "ukrainian-riding": [
    "/horses/expansion/ukrainian-riding-1.jpg"
  ],
  "swedish-warmblood": [
    "/horses/expansion/swedish-warmblood-1.jpg"
  ],
  "soviet-heavy-draft": [
    "/horses/expansion/soviet-heavy-draft-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Soviet_Heavy_Draft._Sevastopol_Zoo..JPG/500px-Soviet_Heavy_Draft._Sevastopol_Zoo..JPG"
  ],
  "vyatka": [
    "/horses/expansion/vyatka-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Vyatka_Gelding_1899.jpg/500px-Vyatka_Gelding_1899.jpg"
  ],
  "westphalian": [
    "/horses/expansion/westphalian-1.jpg"
  ],
  "yonaguni-horse": [
    "/horses/expansion/yonaguni-horse-1.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Yonaguni_Horse_%40_Rokkosan_Pasture.jpg/250px-Yonaguni_Horse_%40_Rokkosan_Pasture.jpg",
    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Yonaguni_horse_5.jpg/960px-Yonaguni_horse_5.jpg"
  ],
  "zaniskari": [
    "/horses/expansion/zaniskari-1.jpg"
  ]
}

export const expansionAlternatePhotos: Record<string, BreedPhoto[]> = Object.fromEntries(
  Object.entries(expansionPhotoSources).map(([id, sources]) => [id, sources.slice(1).map((source, index) => ({ src: expansionPhotoUrls[id][index + 1], source }))])
)
