import type { BreedSeed } from './data'

const commonsPhoto = (file: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=1200`

export const extraBreeds: BreedSeed[] = [
  {
    id: 'ljutomer-trotter', name: 'Ljutomer Trotter', image: '/horses/ljutomer-trotter-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Ljutomer_(3).jpg',
    location: 'Ljutomer', country: 'Slovenia', lat: 46.52, lng: 16.20,
    hint: 'A light harness horse from the Pannonian plains, closely tied to Slovenia’s oldest trotting tradition.',
    fact: 'Farmers around Ljutomer began breeding trotters in the 19th century, creating the horse at the heart of Slovenia’s organized harness racing tradition.',
    tags: ['Trotter', 'Slovenian', 'Rare'], source: 'https://culture.gov.si/en/Ljutomer_Trotter_Museum',
  },
  {
    id: 'cape-boerperd', name: 'Cape Boerperd', image: '/horses/cape-boerperd-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Boerperd.JPG',
    location: 'Cape region', country: 'South Africa', lat: -33.93, lng: 18.42,
    hint: 'A tough, comfortable South African riding horse descended from the old Cape horse tradition.',
    fact: 'The Cape Boerperd preserves a South African type selected by farmers for endurance, sure-footedness, temperament, and versatile farm work.',
    tags: ['Gaited', 'South African', 'Hardy'], source: 'http://capeboerperd.co.za/',
  },
  {
    id: 'nonius', name: 'Nonius', image: '/horses/nonius-1.jpg',
    imageSource: 'https://mezohegyesbirtok.hu/hu/noniusz/',
    location: 'Mezőhegyes', country: 'Hungary', lat: 46.32, lng: 20.82,
    hint: 'Usually dark, substantial, and Roman-nosed, this Hungarian breed was built for harness and farm work.',
    fact: 'The Nonius was founded at the Mezőhegyes State Stud from the Anglo-Norman stallion Nonius Senior and became a celebrated military and agricultural horse.',
    tags: ['Hungarian', 'Driving', 'Historic stud'], source: 'https://mlosz.hu/en/breeds/nonius',
  },
  {
    id: 'gidran', name: 'Gidran', image: '/horses/gidran-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:HPIM2487.JPG',
    location: 'Mezőhegyes', country: 'Hungary', lat: 46.32, lng: 20.82,
    hint: 'A rare Hungarian Anglo-Arabian that is traditionally chestnut and carries a strong cavalry stamp.',
    fact: 'The Gidran arose at Mezőhegyes from Arabian and Thoroughbred-influenced stock and became one of Hungary’s traditional military horse breeds.',
    tags: ['Hungarian', 'Anglo-Arabian', 'Rare'], source: 'https://mlosz.hu/en/breeds/gidran',
  },
  {
    id: 'furioso-north-star', name: 'Furioso–North Star', image: '/horses/furioso-north-star-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Furioso-Przedswit_Polish_breed_1.jpg',
    location: 'Mezőhegyes', country: 'Hungary', lat: 46.32, lng: 20.82,
    hint: 'A sturdy Hungarian warmblood shaped by two influential English Thoroughbred stallion lines.',
    fact: 'The Furioso–North Star developed at Mezőhegyes around the Thoroughbred stallions Furioso and North Star, producing a versatile riding and carriage horse.',
    tags: ['Hungarian', 'Warmblood', 'Cavalry'], source: 'https://mlosz.hu/en/breeds/furioso-north-star',
  },
  {
    id: 'kisber-felver', name: 'Kisbér Felver', image: '/horses/kisber-felver-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Whiskey,_egy_Kisb%C3%A9ri_f%C3%A9lv%C3%A9r1.jpg',
    location: 'Kisbér', country: 'Hungary', lat: 47.50, lng: 18.03,
    hint: 'An elegant Hungarian half-bred developed for cavalry use with a strong Thoroughbred influence.',
    fact: 'The Kisbér Felver was created at the Kisbér stud as a sound, refined riding horse, combining local mares with Thoroughbred and other quality bloodlines.',
    tags: ['Hungarian', 'Sport horse', 'Rare'], source: 'https://mlosz.hu/en/breeds/kisberi-felver',
  },
  {
    id: 'shagya-arabian', name: 'Shagya Arabian', image: '/horses/shagya-arabian-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Shagya_horses_Kabiuk.jpg',
    location: 'Bábolna', country: 'Hungary', lat: 47.64, lng: 17.98,
    hint: 'Larger and more substantial than many desert Arabians, yet recognizably Arabian in type.',
    fact: 'The breed was developed in the Austro-Hungarian studs, especially Bábolna, to combine Arabian stamina and refinement with greater size and riding utility.',
    tags: ['Hungarian', 'Arabian', 'Endurance'], source: 'https://mlosz.hu/en/breeds/shagya-arabian',
  },
  {
    id: 'hucul', name: 'Hucul', image: '/horses/hucul-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Hucul_(horse).jpg',
    location: 'Carpathian Mountains', country: 'Ukraine', lat: 48.10, lng: 24.50,
    hint: 'A compact Carpathian mountain horse with primitive markings, hard feet, and remarkable sure-footedness.',
    fact: 'The Hucul developed among mountain communities of the eastern Carpathians and remains closely associated with Hutsul culture across several modern countries.',
    tags: ['Mountain', 'Primitive', 'Carpathian'], source: 'https://en.wikipedia.org/wiki/Hucul_pony',
  },
  {
    id: 'kladruber', name: 'Kladruber', image: '/horses/kladruber-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Kladruber.jpg',
    location: 'Kladruby nad Labem', country: 'Czechia', lat: 50.06, lng: 15.49,
    hint: 'A tall ceremonial carriage horse, usually gray or black, with a distinctive convex profile.',
    fact: 'Bred for Habsburg court ceremony at Kladruby nad Labem, the Kladruber is among the oldest purpose-bred carriage horses still surviving.',
    tags: ['Baroque', 'Driving', 'Czech'], source: 'https://en.wikipedia.org/wiki/Kladruber',
  },
  {
    id: 'konik', name: 'Konik', image: '/horses/konik-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Konik_horses_(Equus_caballus_var._konik)_in_the_Gendtse_Waard.jpg',
    location: 'Biłgoraj region', country: 'Poland', lat: 50.54, lng: 22.72,
    hint: 'A small mouse-dun Polish horse with a dark dorsal stripe, often used in conservation grazing.',
    fact: 'The modern Konik was shaped from hardy Polish farm horses and is now widely used to maintain semi-wild grassland and wetland habitats.',
    tags: ['Primitive', 'Polish', 'Conservation'], source: 'https://en.wikipedia.org/wiki/Konik',
  },
  {
    id: 'yakutian', name: 'Yakutian Horse', image: '/horses/yakutian-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:A_Yakutian_horse_(9762345674).jpg',
    location: 'Sakha Republic', country: 'Russia', lat: 62.03, lng: 129.73,
    hint: 'A compact Siberian horse with an extraordinarily dense winter coat and extreme cold tolerance.',
    fact: 'Yakutian horses live outdoors through the severe winters of the Sakha Republic, foraging beneath snow and adapting to temperatures far below freezing.',
    tags: ['Siberian', 'Cold-climate', 'Primitive'], source: 'https://en.wikipedia.org/wiki/Yakutian_horse',
  },
  {
    id: 'caspian', name: 'Caspian Horse', image: '/horses/caspian-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Caspian_Stallion_1.jpg',
    location: 'Caspian coast', country: 'Iran', lat: 36.84, lng: 50.55,
    hint: 'A tiny but horse-proportioned Iranian breed, refined rather than pony-like.',
    fact: 'Long thought lost, the Caspian was brought to wider attention in northern Iran in the 1960s and is valued for its ancient-looking, finely built type.',
    tags: ['Ancient type', 'Iranian', 'Rare'], source: 'https://en.wikipedia.org/wiki/Caspian_horse',
  },
  {
    id: 'kathiawari', name: 'Kathiawari', image: '/horses/kathiawari-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Kathiawari_1.jpg',
    location: 'Kathiawar peninsula', country: 'India', lat: 21.64, lng: 70.95,
    hint: 'A desert-adapted Indian riding horse whose inward-curving ears may meet at the tips.',
    fact: 'The Kathiawari developed on Gujarat’s Kathiawar peninsula as a hardy cavalry and endurance horse, sharing its famous curved ears with the Marwari.',
    tags: ['Indian', 'Desert', 'Curved ears'], source: 'https://en.wikipedia.org/wiki/Kathiawari_horse',
  },
  {
    id: 'sorraia', name: 'Sorraia', image: '/horses/sorraia-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Vale_de_Zebro_Sorraia_Stallions.JPG',
    location: 'Sorraia River basin', country: 'Portugal', lat: 38.99, lng: -8.86,
    hint: 'A rare Iberian landrace, typically dun or grullo with a dorsal stripe and dark points.',
    fact: 'The Sorraia survived in the wetlands of Portugal’s Tagus and Sorraia river country and preserves a distinctive primitive Iberian type.',
    tags: ['Primitive', 'Iberian', 'Rare'], source: 'https://en.wikipedia.org/wiki/Sorraia',
  },
  {
    id: 'dales-pony', name: 'Dales Pony', image: '/horses/dales-pony-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Dalespony.jpg',
    location: 'Pennine dales', country: 'England', lat: 54.28, lng: -2.20,
    hint: 'A powerful northern English pack pony, usually black, with abundant mane, tail, and lower-leg feather.',
    fact: 'The Dales Pony carried heavy loads across the Pennines, including ore from lead mines, and is known for strength, stamina, and a brisk trot.',
    tags: ['Pony', 'Pack horse', 'English'], source: 'https://en.wikipedia.org/wiki/Dales_pony',
  },
  {
    id: 'eriskay-pony', name: 'Eriskay Pony', image: '/horses/eriskay-pony-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Eriskay_pony_beinn_sciathan.jpg',
    location: 'Eriskay, Outer Hebrides', country: 'Scotland', lat: 57.07, lng: -7.31,
    hint: 'A small, usually gray island pony shaped by Atlantic weather and crofting life.',
    fact: 'The Eriskay is one of the last surviving Hebridean pony types, traditionally used by island crofters for carrying peat, seaweed, and people.',
    tags: ['Pony', 'Island', 'Endangered'], source: 'https://en.wikipedia.org/wiki/Eriskay_pony',
  },
  {
    id: 'bardigiano', name: 'Bardigiano', image: '/horses/bardigiano-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Bardigiano.JPG',
    location: 'Bardi, Emilia-Romagna', country: 'Italy', lat: 44.63, lng: 9.73,
    hint: 'A compact, dark-coated mountain horse from the northern Apennines.',
    fact: 'Named for the town of Bardi, the Bardigiano developed as a sturdy farm, pack, and riding horse suited to the steep country of Emilia-Romagna.',
    tags: ['Mountain', 'Italian', 'Rare'], source: 'https://en.wikipedia.org/wiki/Bardigiano',
  },
  {
    id: 'maremmano', name: 'Maremmano', image: '/horses/maremmano-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Maremmano_horse_Tuscany_2.jpg',
    location: 'Maremma', country: 'Italy', lat: 42.76, lng: 11.11,
    hint: 'A rugged Italian stock horse traditionally ridden by butteri cattle herders.',
    fact: 'The Maremmano developed in the marshy coastal country of Tuscany and Lazio as a hardy mount for livestock work in rough terrain.',
    tags: ['Stock horse', 'Italian', 'Hardy'], source: 'https://en.wikipedia.org/wiki/Maremmano',
  },
  {
    id: 'nordlandshest', name: 'Nordlandshest/Lyngshest', image: '/horses/nordlandshest-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Bj%C3%B8rkem%C3%A5ne.jpg',
    location: 'Northern Norway', country: 'Norway', lat: 69.65, lng: 18.96,
    hint: 'A small, versatile northern Norwegian horse once reduced to only a handful of breeding animals.',
    fact: 'The Nordlandshest/Lyngshest is an old farm and transport breed from northern Norway, rebuilt from a dangerously small population after World War II.',
    tags: ['Nordic', 'Pony', 'Rare'], source: 'https://en.wikipedia.org/wiki/Nordlandshest/Lyngshest',
  },
  {
    id: 'gotland-russ', name: 'Gotland Russ', image: '/horses/gotland-russ-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Gotlandsruss-slottsskogen-goteborg.jpg',
    location: 'Gotland', country: 'Sweden', lat: 57.47, lng: 18.49,
    hint: 'A small Swedish forest pony with ancient roots on a Baltic island.',
    fact: 'The Gotland Russ has lived on Gotland for centuries; semi-feral ponies still graze the Lojsta heath while the breed also excels in harness racing.',
    tags: ['Pony', 'Swedish', 'Island'], source: 'https://en.wikipedia.org/wiki/Gotland_pony',
  },
  {
    id: 'noriker', name: 'Noriker', image: '/horses/noriker-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Noriker_horseGrauschimmelstute.JPG',
    location: 'Austrian Alps', country: 'Austria', lat: 47.30, lng: 13.10,
    hint: 'A sure-footed Alpine draft horse that may appear in dramatic leopard-spotted coats.',
    fact: 'The Noriker is an old Austrian mountain draft breed, selected for power, balance, and dependable work on steep Alpine farms and roads.',
    tags: ['Draft', 'Alpine', 'Spotted'], source: 'https://en.wikipedia.org/wiki/Noriker',
  },
  {
    id: 'cleveland-bay', name: 'Cleveland Bay', image: '/horses/cleveland-bay-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Cleveland_Bay_hw_crop.jpg',
    location: 'Cleveland, Yorkshire', country: 'England', lat: 54.43, lng: -1.14,
    hint: 'Britain’s oldest established horse breed: always bay, substantial, and traditionally used for coaches.',
    fact: 'The Cleveland Bay developed in northeast England from versatile pack horses known as Chapman horses and later became prized for carriage work.',
    tags: ['Driving', 'English', 'Endangered'], source: 'https://en.wikipedia.org/wiki/Cleveland_Bay',
  },
  {
    id: 'giara', name: 'Giara Horse', image: '/horses/giara-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Cavallino_della_Giara-cropped_02.jpg',
    location: 'Giara di Gesturi', country: 'Italy', lat: 39.75, lng: 8.98,
    hint: 'A small, hardy Sardinian horse living semi-ferally on a high basalt plateau.',
    fact: 'The Giara horse is strongly associated with the Giara di Gesturi plateau, where free-ranging herds survive hot, dry summers around seasonal pools.',
    tags: ['Island', 'Semi-feral', 'Sardinian'], source: 'https://en.wikipedia.org/wiki/Giara_horse',
  },
  {
    id: 'garrano', name: 'Garrano', image: '/horses/garrano-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Garranos_fight.jpg',
    location: 'Peneda-Gerês', country: 'Portugal', lat: 41.80, lng: -8.15,
    hint: 'A small, dark, sure-footed horse of the mountains of northern Portugal and Galicia.',
    fact: 'The Garrano is an ancient Iberian landrace still found in free-ranging groups in northern Portugal, where it was long used for pack work and transport.',
    tags: ['Primitive', 'Iberian', 'Mountain'], source: 'https://en.wikipedia.org/wiki/Garrano',
  },
  {
    id: 'kerry-bog-pony', name: 'Kerry Bog Pony', image: '/horses/kerry-bog-pony-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Kerry_bog_pony_stallion.jpg',
    location: 'County Kerry', country: 'Ireland', lat: 52.15, lng: -9.57,
    hint: 'A compact Irish pony bred to carry loads across soft, wet peat ground.',
    fact: 'The Kerry Bog Pony worked the bogs of southwest Ireland, hauling peat and farm loads; the breed was rediscovered close to extinction in the late 20th century.',
    tags: ['Pony', 'Irish', 'Rare'], source: 'https://en.wikipedia.org/wiki/Kerry_Bog_Pony',
  },
  {
    id: 'exmoor-pony', name: 'Exmoor Pony', image: '/horses/exmoor-pony-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Exmoor_pony%27s_in_mild_avondlicht._Locatie,_natuurgebied_Delleboersterheide_%E2%80%93_Catspoele.jpg',
    location: 'Exmoor', country: 'England', lat: 51.13, lng: -3.64,
    hint: 'A hardy moorland pony with a mealy muzzle and hooded eyes adapted to wind and rain.',
    fact: 'Exmoor ponies have lived for centuries on the open moors of southwest England and retain a remarkably uniform, weather-resistant native type.',
    tags: ['Pony', 'Primitive', 'English'], source: 'https://en.wikipedia.org/wiki/Exmoor_pony',
  },
  {
    id: 'camargue', name: 'Camargue Horse', image: '/horses/camargue-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Saint-Laurent-d%27Aigouze_-_Camargue_horses_-_04.jpg',
    location: 'Camargue', country: 'France', lat: 43.53, lng: 4.50,
    hint: 'A compact gray horse of the Rhône delta, traditionally used by gardians to work black cattle.',
    fact: 'Camargue horses are born dark and turn gray with age; semi-feral herds have long inhabited the wetlands and salt marshes of southern France.',
    tags: ['Wetland', 'French', 'Gray'], source: 'https://en.wikipedia.org/wiki/Camargue_horse',
  },
  {
    id: 'poitevin', name: 'Poitevin Mulassier', image: '/horses/poitevin-1.jpg',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Poitevins01_SDA2011.JPG',
    location: 'Poitou', country: 'France', lat: 46.33, lng: -0.46,
    hint: 'A large, shaggy French draft horse historically prized for producing powerful mules.',
    fact: 'The Poitevin developed in the marshes of western France and was crossed with Baudet du Poitou donkeys to produce the once-famous Poitevin mule.',
    tags: ['Draft', 'French', 'Endangered'], source: 'https://en.wikipedia.org/wiki/Poitevin_horse',
  },
  {
    id: 'mangalarga-marchador', name: 'Mangalarga Marchador', image: commonsPhoto('Mangalarga Marchador.jpg'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Mangalarga_Marchador.jpg',
    location: 'Minas Gerais', country: 'Brazil', lat: -20.14, lng: -44.20,
    hint: 'Look for a refined but substantial saddle horse with a smooth, ground-covering four-beat gait.',
    fact: 'The Mangalarga Marchador descends from Iberian horses brought to Brazil and was developed on farms in Minas Gerais. It is known for the marcha batida and marcha picada, comfortable intermediate gaits that can be maintained over long distances.',
    tags: ['Gaited', 'Brazilian', 'Saddle horse'], source: 'https://en.wikipedia.org/wiki/Mangalarga_Marchador',
  },
  {
    id: 'boulonnais', name: 'Boulonnais', image: commonsPhoto('Jument boulonnaise.jpg'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Jument_boulonnaise.jpg',
    location: 'Boulonnais, Pas-de-Calais', country: 'France', lat: 50.73, lng: 1.62,
    hint: 'A massive draft horse with unusually silky skin, a refined head, and a coat most often seen in gray.',
    fact: 'Sometimes called the White Marble Horse, the Boulonnais combines draft power with a notably elegant head and energetic action. Its lighter mareyeur type once hauled fresh fish rapidly from the Channel coast toward Paris.',
    tags: ['Draft', 'Gray', 'Rare'], source: 'https://en.wikipedia.org/wiki/Boulonnais_horse',
  },
  {
    id: 'comtois', name: 'Comtois', image: commonsPhoto('Cheval Comtois 001.JPG'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Cheval_Comtois_001.JPG',
    location: 'Franche-Comté', country: 'France', lat: 47.24, lng: 6.02,
    hint: 'A compact, muscular draft horse commonly showing a rich copper coat with a pale flaxen mane and tail.',
    fact: 'The Comtois is an old mountain draft horse selected for forestry, farming, and hauling on difficult ground. Modern examples are especially associated with silver-dapple or flaxen chestnut coloring and a willing working temperament.',
    tags: ['Draft', 'Flaxen', 'Mountain'], source: 'https://en.wikipedia.org/wiki/Comtois_horse',
  },
  {
    id: 'campolina', name: 'Campolina', image: commonsPhoto('Black Campolina male 2 years.JPG'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Black_Campolina_male_2_years.JPG',
    location: 'Entre Rios de Minas, Minas Gerais', country: 'Brazil', lat: -20.67, lng: -44.07,
    hint: 'A tall gaited saddle horse with a strong arched neck and a characteristically convex facial profile.',
    fact: 'Cassiano Campolina began the breed in the 1870s from a mare named Medeia and carefully selected descendants for size, presence, and comfortable travel. Campolinas may perform several forms of the marcha and occur in many colors.',
    tags: ['Gaited', 'Brazilian', 'Convex profile'], source: 'https://en.wikipedia.org/wiki/Campolina',
  },
  {
    id: 'zemaitukas', name: 'Žemaitukas', image: commonsPhoto('Didysis zemaitukas 1.jpg'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Didysis_zemaitukas_1.jpg',
    location: 'Samogitia', country: 'Lithuania', lat: 55.85, lng: 22.25,
    hint: 'A small, tough horse with a broad forehead, clean legs, hard feet, and great strength for its height.',
    fact: 'The Žemaitukas is an ancient light-horse type documented since medieval times. It served as a farm, riding, and military horse, survived several severe population crashes, and remains a treasured but endangered breed.',
    tags: ['Primitive', 'Lithuanian', 'Endangered'], source: 'https://en.wikipedia.org/wiki/%C5%BDemaitukas',
  },
  {
    id: 'karabakh', name: 'Karabakh', image: commonsPhoto('Qarabağ atları Şəki Atçılıq Mərkəzində.jpg'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Qaraba%C4%9F_atlar%C4%B1_%C5%9E%C9%99ki_At%C3%A7%C4%B1l%C4%B1q_M%C9%99rk%C9%99zind%C9%99.jpg',
    location: 'Karabakh', country: 'Azerbaijan', lat: 39.81, lng: 46.75,
    hint: 'A compact mountain saddle horse valued for sure-footed speed, a deep chest, and a fine, alert head.',
    fact: 'The Karabakh was refined in the khanates of the southern Caucasus as a fast riding and racing horse. Golden chestnut coloring is especially admired, and the breed has contributed to several neighboring horse populations.',
    tags: ['Mountain', 'Riding', 'Rare'], source: 'https://en.wikipedia.org/wiki/Karabakh_horse',
  },
  {
    id: 'breton', name: 'Breton', image: commonsPhoto('St-Guyomard - Jument bretonne broutant.jpg'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:St-Guyomard_-_Jument_bretonne_broutant.jpg',
    location: 'Brittany', country: 'France', lat: 48.20, lng: -2.93,
    hint: 'A broad, energetic draft horse, often chestnut with a flaxen mane, whose brisk trot belies its heavy build.',
    fact: 'The Breton includes both heavier draft and lighter Postier types. It became renowned for farm and artillery work, and the quick-moving Postier was shaped in part by Norfolk Trotter and Hackney influence.',
    tags: ['Draft', 'Chestnut', 'Postier'], source: 'https://en.wikipedia.org/wiki/Breton_horse',
  },
  {
    id: 'ardennais', name: 'Ardennais', image: commonsPhoto('Ardennais 1.JPG'),
    imageSource: 'https://commons.wikimedia.org/wiki/File:Ardennais_1.JPG',
    location: 'Ardennes', country: 'Belgium and France', lat: 49.85, lng: 4.65,
    hint: 'A low-set, immensely muscular draft horse with short strong legs, a thick neck, and a calm expression.',
    fact: 'The Ardennais is among Europe’s oldest heavy horse types and was used for agriculture, forestry, artillery, and difficult transport. Despite its compact height, it is exceptionally powerful and adapted to rough going.',
    tags: ['Draft', 'Cold-blood', 'Ancient type'], source: 'https://en.wikipedia.org/wiki/Ardennais',
  },
]
